import fs from "node:fs";
import path from "node:path";

// Word-boundary-safe fixes: unaccented (WRONG) -> correctly accented French spelling.
// Every entry here is a word that has NO valid unaccented French spelling - safe to
// blind-replace inside string literals. Longer/more-specific entries first isn't required
// since we match with \b...\b, but plural/gender variants are listed explicitly.
const DICTIONARY = [
  ["personnalisees", "personnalisées"], ["personnalises", "personnalisés"],
  ["personnalisee", "personnalisée"], ["personnalise", "personnalisé"],
  ["preferences", "préférences"], ["preference", "préférence"],
  ["parametres", "paramètres"], ["parametre", "paramètre"],
  ["connectees", "connectées"], ["connectes", "connectés"],
  ["connectee", "connectée"], ["connecte", "connecté"],
  ["deconnectee", "déconnectée"], ["deconnecte", "déconnecté"], ["deconnecter", "déconnecter"],
  ["actualisees", "actualisées"], ["actualises", "actualisés"],
  ["actualisee", "actualisée"], ["actualise", "actualisé"],
  ["evenements", "événements"], ["evenement", "événement"],
  ["necessaires", "nécessaires"], ["necessaire", "nécessaire"],
  ["creees", "créées"], ["crees", "créés"], ["creee", "créée"], ["cree", "créé"], ["creer", "créer"], ["creez", "créez"],
  ["modifiees", "modifiées"], ["modifies", "modifiés"], ["modifiee", "modifiée"], ["modifie", "modifié"],
  ["supprimees", "supprimées"], ["supprimes", "supprimés"], ["supprimee", "supprimée"], ["supprime", "supprimé"],
  ["generees", "générées"], ["generes", "générés"], ["generee", "générée"], ["genere", "généré"], ["generez", "générez"],
  ["recuperees", "récupérées"], ["recuperes", "récupérés"], ["recuperee", "récupérée"], ["recupere", "récupère"],
  ["terminees", "terminées"], ["termines", "terminés"], ["terminee", "terminée"], ["termine", "terminé"],
  ["preparees", "préparées"], ["prepares", "préparés"], ["preparee", "préparée"], ["prepare", "préparé"],
  ["reussies", "réussies"], ["reussis", "réussis"], ["reussie", "réussie"], ["reussi", "réussi"],
  ["echouees", "échouées"], ["echoues", "échoués"], ["echouee", "échouée"], ["echoue", "échoué"],
  ["indisponibles", "indisponibles"], ["indisponible", "indisponible"],
  ["selectionnees", "sélectionnées"], ["selectionnes", "sélectionnés"],
  ["selectionnee", "sélectionnée"], ["selectionne", "sélectionné"], ["selectionner", "sélectionner"],
  ["references", "références"], ["reference", "référence"],
  ["dernieres", "dernières"], ["derniers", "derniers"], ["derniere", "dernière"],
  ["premieres", "premières"], ["premiere", "première"],
  ["entieres", "entières"], ["entiere", "entière"],
  ["securisees", "sécurisées"], ["securises", "sécurisés"], ["securisee", "sécurisée"], ["securise", "sécurisé"],
  ["activites", "activités"], ["activite", "activité"],
  ["priorites", "priorités"], ["priorite", "priorité"],
  ["operations", "opérations"], ["operation", "opération"],
  ["recentes", "récentes"], ["recents", "récents"], ["recente", "récente"],
  ["donnees", "données"], ["donnee", "donnée"],
  ["reseau", "réseau"], ["reseaux", "réseaux"],
  ["systeme", "système"], ["systemes", "systèmes"],
  ["utilisateurs", "utilisateurs"], ["utilisateur", "utilisateur"],
  ["categories", "catégories"], ["categorie", "catégorie"],
  ["resultats", "résultats"], ["resultat", "résultat"],
  ["erreurs", "erreurs"], ["erreur", "erreur"],
  ["reponses", "réponses"], ["reponse", "réponse"],
  ["acces", "accès"],
  ["verifiees", "vérifiées"], ["verifies", "vérifiés"], ["verifiee", "vérifiée"], ["verifie", "vérifié"],
  ["verifier", "vérifier"], ["verifiez", "vérifiez"], ["verification", "vérification"],
  ["identifiees", "identifiées"], ["identifies", "identifiés"], ["identifiee", "identifiée"], ["identifie", "identifié"],
  ["specifiees", "spécifiées"], ["specifies", "spécifiés"], ["specifiee", "spécifiée"], ["specifie", "spécifié"],
  ["detaillees", "détaillées"], ["detailles", "détaillés"], ["detaillee", "détaillée"], ["detaille", "détaillé"],
  ["integrees", "intégrées"], ["integres", "intégrés"], ["integree", "intégrée"], ["integre", "intégré"],
  ["importees", "importées"], ["importes", "importés"], ["importee", "importée"], ["importe", "importé"],
  ["exportees", "exportées"], ["exportes", "exportés"], ["exportee", "exportée"], ["exporte", "exporté"],
  ["programmees", "programmées"], ["programmes", "programmés"], ["programmee", "programmée"], ["programme", "programmé"],
  ["traitees", "traitées"], ["traites", "traités"], ["traitee", "traitée"], ["traite", "traité"],
  ["etre", "être"],
  ["meme", "même"], ["memes", "mêmes"],
  ["deja", "déjà"],
  ["tres", "très"],
  ["apres", "après"],
  ["annees", "années"], ["annee", "année"],
  ["complete", "complète"], ["completes", "complètes"], ["complet", "complet"],
  ["fenetres", "fenêtres"], ["fenetre", "fenêtre"],
  ["confidentialite", "confidentialité"],
  ["revocable", "révocable"],
  ["prive", "privé"], ["privee", "privée"], ["prives", "privés"], ["privees", "privées"],
  ["publiee", "publiée"], ["publiees", "publiées"], ["publies", "publiés"],
  ["approuve", "approuvé"], ["approuvee", "approuvée"],
  ["controles", "contrôles"], ["controle", "contrôle"],
  ["boucle", "boucle"],
  ["independant", "indépendant"], ["independants", "indépendants"], ["independante", "indépendante"],
  ["conçu", "conçu"],
  ["concu", "conçu"],
  ["decochez", "décochez"],
  ["homepage", "homepage"],
  ["installee", "installée"],
  ["notez", "notez"],
  ["associez", "associez"],
  ["granulaires", "granulaires"],
  ["correspond", "correspond"],
  ["collez", "collez"],
  ["ci-dessous", "ci-dessous"],
  ["egalement", "également"],
  ["generalement", "généralement"],
  ["specifique", "spécifique"], ["specifiques", "spécifiques"],
  ["cle", "clé"], ["cles", "clés"],
  ["americain", "américain"],
  ["etat", "état"], ["etats", "états"],
  ["reglages", "réglages"], ["reglage", "réglage"],
  ["meteo", "météo"],
  ["desormais", "désormais"],
  ["appelee", "appelée"], ["appeles", "appelés"], ["appele", "appelé"],
  ["details", "détails"], ["detail", "détail"],
  ["fraicheur", "fraîcheur"],
  ["ecran", "écran"], ["ecrans", "écrans"],
  ["decrivait", "décrivait"], ["decrit", "décrit"],
  ["etait", "était"], ["etaient", "étaient"],
  ["utilisees", "utilisées"], ["utilises", "utilisés"], ["utilisee", "utilisée"], ["utilise", "utilisé"], ["utiliser", "utiliser"],
  ["regles", "règles"], ["regle", "règle"],
  ["precises", "précises"], ["precis", "précis"], ["precise", "précise"],
  ["declenchent", "déclenchent"], ["declenche", "déclenche"],
  ["densites", "densités"], ["densite", "densité"],
  ["previsions", "prévisions"], ["prevision", "prévision"],
  ["humidite", "humidité"],
  ["tronquee", "tronquée"], ["tronque", "tronqué"],
  ["integrations", "intégrations"], ["integration", "intégration"],
  ["allegee", "allégée"], ["allege", "allégé"],
  ["repondre", "répondre"],
  ["generations", "générations"], ["generation", "génération"],
  ["icones", "icônes"], ["icone", "icône"],
  ["generiques", "génériques"], ["generique", "générique"],
  ["precedents", "précédents"], ["precedente", "précédente"], ["precedent", "précédent"],
  ["periodiques", "périodiques"], ["periodique", "périodique"],
  ["entierement", "entièrement"],
  ["cablees", "câblées"], ["cables", "câblés"], ["cablee", "câblée"], ["cable", "câblé"],
  ["dediee", "dédiée"], ["dedies", "dédiés"], ["dedie", "dédié"],
  ["generales", "générales"], ["generaux", "généraux"], ["generale", "générale"], ["general", "général"],
  ["ameliorations", "améliorations"], ["amelioration", "amélioration"], ["ameliore", "amélioré"], ["ameliorer", "améliorer"],
  ["controle", "contrôle"], ["controles", "contrôles"],
  ["oubliee", "oubliée"], ["oublies", "oubliés"], ["oublie", "oublié"], ["oublier", "oublier"],
  ["disponibles", "disponibles"], ["disponible", "disponible"],
  ["retablir", "rétablir"],
  ["reessaie", "réessaie"], ["reessayer", "réessayer"],
  ["mesuree", "mesurée"], ["mesure", "mesuré"],
  ["ancienne", "ancienne"],
  ["revoquer", "révoquer"],
  ["periode", "période"], ["periodes", "périodes"],
  ["theme", "thème"], ["themes", "thèmes"],
  ["derniere", "dernière"],
  ["numero", "numéro"], ["numeros", "numéros"],
  ["categorie", "catégorie"], ["categories", "catégories"],
  ["libere", "libéré"], ["liberee", "libérée"],
  ["separee", "séparée"], ["separes", "séparés"], ["separe", "séparé"],
  ["repete", "répété"], ["repetee", "répétée"],
  ["repartie", "répartie"], ["reparti", "réparti"],
  ["repartition", "répartition"],
  ["temoin", "témoin"], ["temoins", "témoins"],
  ["succes", "succès"],
  ["proces", "procès"],
  ["progres", "progrès"],
  ["pres", "près"],
  ["exces", "excès"],
  ["expres", "exprès"],
  ["interet", "intérêt"], ["interets", "intérêts"],
  ["preexistant", "préexistant"], ["preexistante", "préexistante"],
  ["preparation", "préparation"],
  ["decalage", "décalage"],
  ["desencombre", "désencombré"], ["desencombree", "désencombrée"],
  ["instantanement", "instantanément"], ["instantanees", "instantanées"], ["instantanee", "instantanée"],
  ["regroupees", "regroupées"], ["regroupes", "regroupés"], ["regroupee", "regroupée"], ["regroupe", "regroupé"],
  ["decochee", "décochée"],
  ["reflete", "reflète"], ["refletent", "reflètent"],
  ["propage", "propage"],
  ["propose", "propose"],
  ["expose", "expose"],
  ["libres", "libres"], ["libre", "libre"],
  ["fonctionnalite", "fonctionnalité"], ["fonctionnalites", "fonctionnalités"],
  ["securite", "sécurité"],
  ["qualite", "qualité"], ["qualites", "qualités"],
  ["quantite", "quantité"],
  ["capacite", "capacité"], ["capacites", "capacités"],
  ["possibilite", "possibilité"], ["possibilites", "possibilités"],
  ["disponibilite", "disponibilité"],
  ["responsabilite", "responsabilité"],
  ["compatibilite", "compatibilité"],
  ["visibilite", "visibilité"],
  ["specificite", "spécificité"],
  ["complexite", "complexité"],
  ["simplicite", "simplicité"],
  ["rapidite", "rapidité"],
  ["stabilite", "stabilité"],
  ["fiabilite", "fiabilité"],
  ["flexibilite", "flexibilité"],
  ["polyvalence", "polyvalence"],
  ["intensite", "intensité"],
  ["clarte", "clarté"],
  ["realite", "réalité"],
  ["totalite", "totalité"],
  ["egalite", "égalité"],
  ["diversite", "diversité"],
  ["universite", "université"],
  ["propriete", "propriété"], ["proprietes", "propriétés"],
  ["societe", "société"],
  ["variete", "variété"],
  ["moitie", "moitié"],
  ["cote", "côté"], ["cotes", "côtés"],
  ["role", "rôle"], ["roles", "rôles"],
  ["hote", "hôte"], ["hotes", "hôtes"],
  ["couts", "coûts"], ["cout", "coût"],
  ["gout", "goût"],
  ["fete", "fête"], ["fetes", "fêtes"],
  ["arret", "arrêt"], ["arrets", "arrêts"],
  ["interrompu", "interrompu"],
  ["foret", "forêt"],
  ["bete", "bête"],
  ["tete", "tête"], ["tetes", "têtes"],
  ["fenetre", "fenêtre"], ["fenetres", "fenêtres"],
  ["conquete", "conquête"],
  ["enquete", "enquête"],
  ["honnete", "honnête"],
  ["extreme", "extrême"], ["extremes", "extrêmes"],
  ["supreme", "suprême"],
  ["ere", "ère"],
  ["premiere", "première"], ["premieres", "premières"],
  ["derniere", "dernière"], ["dernieres", "dernières"],
  ["matiere", "matière"], ["matieres", "matières"],
  ["maniere", "manière"], ["manieres", "manières"],
  ["lumiere", "lumière"],
  ["riviere", "rivière"],
  ["frontiere", "frontière"],
  ["carriere", "carrière"],
  ["barriere", "barrière"],
  ["poussiere", "poussière"],
  ["cimetiere", "cimetière"],
  ["infirmiere", "infirmière"],
  ["banniere", "bannière"],
  ["ministere", "ministère"],
  ["mystere", "mystère"],
  ["cratere", "cratère"],
  ["caractere", "caractère"], ["caracteres", "caractères"],
  ["numerique", "numérique"], ["numeriques", "numériques"],
  ["electronique", "électronique"],
  ["energie", "énergie"],
  ["strategie", "stratégie"], ["strategique", "stratégique"],
  ["technologie", "technologie"],
  ["methode", "méthode"], ["methodes", "méthodes"],
  ["periphique", "périphérique"],
  ["synthese", "synthèse"],
  ["hypothese", "hypothèse"],
  ["analyse", "analyse"],
  ["phase", "phase"],
  ["progression", "progression"]
];

// Guard against over-eager entries that would corrupt correct text (e.g. "applique" as a
// standalone verb form is already correct in some contexts - drop ambiguous ones).
const SAFE = DICTIONARY.filter(([from, to]) => from !== to);

// Fixed idioms where the "unaccented" spelling is already grammatically correct as-is -
// never touch these regardless of which dictionary word matches inside them.
const IDIOM_GUARDS = [/n['’]importe/i];

const files = process.argv.slice(2);
let totalReplacements = 0;

for (const filePath of files) {
  let text = fs.readFileSync(filePath, "utf8");
  let fileReplacements = 0;
  text = text.replace(/"([^"\\]|\\.)*"/g, (literal) => {
    let inner = literal.slice(1, -1);
    for (const [from, to] of SAFE) {
      const re = new RegExp(`\\b${from}\\b`, "gi");
      inner = inner.replace(re, (match, offset, whole) => {
        const context = whole.slice(Math.max(0, offset - 15), offset + match.length + 15);
        if (IDIOM_GUARDS.some((guard) => guard.test(context))) return match;
        fileReplacements += 1;
        if (match === match.toUpperCase() && match.length > 1) return to.toUpperCase();
        if (match[0] === match[0].toUpperCase()) return to[0].toUpperCase() + to.slice(1);
        return to;
      });
    }
    return `"${inner}"`;
  });
  if (fileReplacements > 0) {
    fs.writeFileSync(filePath, text, "utf8");
    console.log(`${filePath}: ${fileReplacements} replacements`);
    totalReplacements += fileReplacements;
  }
}
console.log(`\nTotal: ${totalReplacements}`);
