export interface IntegrationConfig {
  id: string;
  name: string;
  category: "oauth" | "api_key" | "webhook";
  badge: string;
  description: string;
  developerUrl: string;
  developerButtonLabel: string;
  docsUrl?: string;
  requiresClientSecret: boolean;
  requiresRedirectUri: boolean;
  secretLabel?: string;
  secretPlaceholder?: string;
  idLabel?: string;
  idPlaceholder?: string;
  callbackPath: string;
  steps: {
    title: string;
    description: string;
    copyValueType?: "homepage" | "callback";
  }[];
}

export const INTEGRATIONS_CONFIG: Record<string, IntegrationConfig> = {
  notion: {
    id: "notion",
    name: "Notion",
    category: "oauth",
    badge: "OAUTH 2.0 / API",
    description: "Accès aux bases de données, pages et blocs de votre espace Notion.",
    developerUrl: "https://www.notion.so/my-integrations",
    developerButtonLabel: "Portail Développeur Notion",
    docsUrl: "https://developers.notion.com/docs/authorization",
    requiresClientSecret: true,
    requiresRedirectUri: true,
    idLabel: "Client ID (ou ID d'intégration)",
    idPlaceholder: "ex: 198a2b3c-4d5e-6f7g-8h9i-0123456789ab",
    secretLabel: "Client Secret (ou Secret interne)",
    secretPlaceholder: "secret_xxxxxxxxxxxxxxxxxxxxxxxxxx",
    callbackPath: "/",
    steps: [
      {
        title: "Créer une intégration",
        description: "Rendez-vous sur le portail développeur Notion et cliquez sur '+ Nouvelle intégration'.",
      },
      {
        title: "Configurer l'accès public ou interne",
        description: "Sélectionnez l'espace de travail associé et choisissez les permissions de lecture/écriture.",
      },
      {
        title: "Renseigner l'URL de redirection (Redirect URI)",
        description: "Dans l'onglet Distribution > Redirect URIs, ajoutez l'URL suivante :",
        copyValueType: "callback",
      },
      {
        title: "Copier le Secret et l'ID",
        description: "Copiez le 'Internal Integration Secret' ou le Client ID / Client Secret et collez-les ci-dessous.",
      },
    ],
  },
  todoist: {
    id: "todoist",
    name: "Todoist",
    category: "oauth",
    badge: "OAUTH 2.0",
    description: "Synchronisation des projets, sections et tâches de votre compte Todoist.",
    developerUrl: "https://developer.todoist.com/appconsole.html",
    developerButtonLabel: "App Console Todoist",
    docsUrl: "https://developer.todoist.com/guides/#oauth",
    requiresClientSecret: true,
    requiresRedirectUri: true,
    idLabel: "Client ID Todoist",
    idPlaceholder: "ex: 7a8b9c0d1e2f3g4h",
    secretLabel: "Client Secret Todoist",
    secretPlaceholder: "ex: 4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d",
    callbackPath: "/",
    steps: [
      {
        title: "Créer une application Todoist",
        description: "Ouvrez l'App Console Todoist et cliquez sur 'Create a new app'. Donnez un nom (ex: ETHONE OS).",
      },
      {
        title: "Renseigner l'URL de redirection OAuth",
        description: "Dans la section 'App Management' > 'OAuth redirect URL', collez l'URL suivante :",
        copyValueType: "callback",
      },
      {
        title: "Renseigner l'URL du service",
        description: "Dans le champ 'App service URL', renseignez l'adresse de votre application :",
        copyValueType: "homepage",
      },
      {
        title: "Récupérer les identifiants",
        description: "Copiez votre Client ID et votre Client Secret générés dans la console.",
      },
    ],
  },
  github: {
    id: "github",
    name: "GitHub",
    category: "oauth",
    badge: "OAUTH 2.0",
    description: "Accès aux repositories, commits et profil utilisateur.",
    developerUrl: "https://github.com/settings/developers",
    developerButtonLabel: "Paramètres Développeur GitHub",
    docsUrl: "https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps",
    requiresClientSecret: true,
    requiresRedirectUri: true,
    idLabel: "Client ID GitHub",
    idPlaceholder: "ex: Ov23li7gnklQJ7ipkgZG",
    secretLabel: "Client Secret GitHub",
    secretPlaceholder: "ex: 5c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d",
    callbackPath: "/",
    steps: [
      {
        title: "Créer une OAuth App",
        description: "Allez dans Settings > Developer settings > OAuth Apps, puis cliquez sur 'New OAuth App'.",
      },
      {
        title: "Renseigner l'URL d'accueil",
        description: "Dans le champ 'Homepage URL', collez l'adresse de votre application :",
        copyValueType: "homepage",
      },
      {
        title: "Renseigner l'URL de rappel",
        description: "Dans le champ 'Authorization callback URL', collez l'URL suivante :",
        copyValueType: "callback",
      },
      {
        title: "Générer le Client Secret",
        description: "Copiez le Client ID et générez un Client Secret. Collez-les ci-dessous.",
      },
    ],
  },
  spotify: {
    id: "spotify",
    name: "Spotify",
    category: "oauth",
    badge: "OAUTH 2.0",
    description: "Lecture en cours, dernières écoutes et profil utilisateur.",
    developerUrl: "https://developer.spotify.com/dashboard",
    developerButtonLabel: "Spotify Developer Dashboard",
    docsUrl: "https://developer.spotify.com/documentation/web-api/tutorials/getting-started",
    requiresClientSecret: true,
    requiresRedirectUri: true,
    idLabel: "Client ID Spotify",
    idPlaceholder: "ex: 6619fbf6315e4e68948dc08532251912",
    secretLabel: "Client Secret Spotify",
    secretPlaceholder: "ex: 1234567890abcdef1234567890abcdef",
    callbackPath: "/",
    steps: [
      {
        title: "Créer une application Spotify",
        description: "Connectez-vous au Spotify Developer Dashboard et cliquez sur 'Create app'.",
      },
      {
        title: "Renseigner l'URL de redirection",
        description: "Dans 'Edit settings' > 'Redirect URIs', ajoutez l'URL suivante :",
        copyValueType: "callback",
      },
      {
        title: "Récupérer les identifiants",
        description: "Copiez le Client ID et le Client Secret affichés dans les paramètres de l'application.",
      },
    ],
  },
  discord: {
    id: "discord",
    name: "Discord",
    category: "oauth",
    badge: "OAUTH 2.0 / LANYARD",
    description: "Présence Discord, statut et activités en temps réel via Lanyard.",
    developerUrl: "https://discord.com/developers/applications",
    developerButtonLabel: "Portail Développeur Discord",
    docsUrl: "https://discord.com/developers/docs/topics/oauth2",
    requiresClientSecret: true,
    requiresRedirectUri: true,
    idLabel: "Client ID Discord",
    idPlaceholder: "ex: 1234567890123456789",
    secretLabel: "Client Secret Discord",
    secretPlaceholder: "ex: abcdef-ghijkl-mnopqr-stuvwxyz",
    callbackPath: "/",
    steps: [
      {
        title: "Créer une application Discord",
        description: "Allez dans le Portail Développeur Discord et créez une nouvelle application.",
      },
      {
        title: "Activer OAuth2",
        description: "Dans 'OAuth2' > 'Redirects', ajoutez l'URL suivante :",
        copyValueType: "callback",
      },
      {
        title: "Récupérer les identifiants",
        description: "Copiez le Client ID et le Client Secret dans 'OAuth2'.",
      },
      {
        title: "Configurer Lanyard",
        description: "Pour la présence, autorisez votre compte sur lanyard.run et notez votre ID utilisateur Discord.",
      },
    ],
  },
  linear: {
    id: "linear",
    name: "Linear",
    category: "api_key",
    badge: "API KEY",
    description: "Issues, cycles et projets de vos équipes Linear.",
    developerUrl: "https://linear.app/settings/api",
    developerButtonLabel: "Paramètres API Linear",
    docsUrl: "https://developers.linear.app/docs/graphql/working-with-the-graphql-api",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    secretLabel: "Token personnel Linear",
    secretPlaceholder: "lin_api_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    callbackPath: "/",
    steps: [
      {
        title: "Ouvrir les paramètres API",
        description: "Rendez-vous dans les paramètres API de votre compte Linear.",
      },
      {
        title: "Créer un token personnel",
        description: "Cliquez sur 'Create key', donnez un nom explicite (ex: ETHONE OS) et confirmez.",
      },
      {
        title: "Copier le token",
        description: "Copiez la clé API générée et collez-la dans le champ ci-dessous.",
      },
    ],
  },
  plex: {
    id: "plex",
    name: "Plex",
    category: "api_key",
    badge: "API KEY",
    description: "Accès à la bibliothèque multimédia et à l'activité de lecture Plex.",
    developerUrl: "https://www.plex.tv/",
    developerButtonLabel: "Compte Plex",
    docsUrl: "https://app.plex.tv/desktop/#!/settings/account",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    idLabel: "URL Plex (optionnel)",
    idPlaceholder: "https://plex.tv",
    secretLabel: "Token Plex",
    secretPlaceholder: "Votre token Plex",
    callbackPath: "/",
    steps: [
      {
        title: "Se connecter au compte Plex",
        description: "Connectez-vous à votre compte Plex.",
      },
      {
        title: "Ouvrir les paramètres du compte",
        description: "Rendez-vous dans les paramètres de votre compte.",
      },
      {
        title: "Afficher le token",
        description: "Affichez la section Informations / Token.",
      },
      {
        title: "Copier le token",
        description: "Copiez le token affiché (ou utilisez l'URL de réclamation fournie).",
      },
      {
        title: "Coller le token",
        description: "Collez le token dans le champ ci-dessous.",
      },
    ],
  },
  jellyfin: {
    id: "jellyfin",
    name: "Jellyfin",
    category: "api_key",
    badge: "API KEY",
    description: "Accès à la bibliothèque multimédia et à l'activité de lecture Jellyfin.",
    developerUrl: "https://jellyfin.org/docs/",
    developerButtonLabel: "Documentation Jellyfin",
    docsUrl: "https://jellyfin.org/docs/general/server/manage-users/",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    idLabel: "URL Jellyfin",
    idPlaceholder: "http://localhost:8096",
    secretLabel: "Clé API Jellyfin",
    secretPlaceholder: "Votre clé API Jellyfin",
    callbackPath: "/",
    steps: [
      {
        title: "Se connecter en administrateur",
        description: "Connectez-vous à votre serveur Jellyfin avec un compte administrateur.",
      },
      {
        title: "Ouvrir le tableau de bord",
        description: "Ouvrez le Tableau de bord (icône en haut à droite).",
      },
      {
        title: "Accéder aux clés d'API",
        description: "Allez dans Avancé > Clés d'API.",
      },
      {
        title: "Générer une clé",
        description: "Cliquez sur le bouton '+' pour générer une nouvelle clé.",
      },
      {
        title: "Nommer la clé",
        description: "Donnez un nom à la clé (ex: ETHONE OS) et confirmez.",
      },
      {
        title: "Coller la clé",
        description: "Copiez la clé affichée et collez-la dans le champ ci-dessous.",
      },
    ],
  },
  emby: {
    id: "emby",
    name: "Emby",
    category: "api_key",
    badge: "API KEY",
    description: "Accès à la bibliothèque multimédia et à l'activité de lecture Emby.",
    developerUrl: "https://dev.emby.media/",
    developerButtonLabel: "Documentation Emby",
    docsUrl: "https://dev.emby.media/",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    idLabel: "URL Emby",
    idPlaceholder: "http://localhost:8096",
    secretLabel: "Clé API Emby",
    secretPlaceholder: "Votre clé API Emby",
    callbackPath: "/",
    steps: [
      {
        title: "Se connecter",
        description: "Connectez-vous à Emby avec un compte administrateur.",
      },
      {
        title: "Ouvrir les clés API",
        description: "Ouvrez le tableau de bord > Avancé > API Keys.",
      },
      {
        title: "Générer une clé",
        description: "Générez une nouvelle clé API.",
      },
      {
        title: "Coller la clé",
        description: "Copiez la clé et collez-la dans le champ ci-dessous.",
      },
    ],
  },
  youtube: {
    id: "youtube",
    name: "YouTube",
    category: "oauth",
    badge: "OAUTH 2.0",
    description: "Abonnements et dernières vidéos de vos chaînes YouTube.",
    developerUrl: "https://developers.google.com/youtube/v3",
    developerButtonLabel: "Console Google Cloud / YouTube",
    docsUrl: "https://console.cloud.google.com/apis/credentials",
    requiresClientSecret: true,
    requiresRedirectUri: true,
    idLabel: "Client ID YouTube",
    idPlaceholder: "Votre Client ID Google Cloud",
    secretLabel: "Client Secret YouTube",
    secretPlaceholder: "Votre Client Secret",
    callbackPath: "/",
    steps: [
      {
        title: "Ouvrir Google Cloud Console",
        description: "Rendez-vous sur Google Cloud Console.",
      },
      {
        title: "Créer un projet",
        description: "Créez un projet Google Cloud ou sélectionnez-en un existant.",
      },
      {
        title: "Activer l'API YouTube",
        description: "Activez l'API YouTube Data v3 dans la bibliothèque d'APIs.",
      },
      {
        title: "Créer un ID client OAuth",
        description: "Dans Identifiants, cliquez sur 'Créer des identifiants' > 'ID client OAuth'.",
      },
      {
        title: "Configurer l'écran de consentement",
        description: "Configurez l'écran de consentement si vous y êtes invité.",
      },
      {
        title: "Récupérer les identifiants",
        description: "Récupérez le Client ID et le Client Secret, puis ajoutez l'URL de redirection fournie :",
        copyValueType: "callback",
      },
    ],
  },
  twitch: {
    id: "twitch",
    name: "Twitch",
    category: "api_key",
    badge: "API KEY",
    description: "Statut live, chaîne et informations de diffusion Twitch.",
    developerUrl: "https://dev.twitch.tv/docs/",
    developerButtonLabel: "Console Twitch Developer",
    docsUrl: "https://dev.twitch.tv/console",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    idLabel: "Client ID Twitch",
    idPlaceholder: "Votre Client ID Twitch",
    secretLabel: "Client Secret Twitch",
    secretPlaceholder: "Votre Client Secret",
    callbackPath: "/",
    steps: [
      {
        title: "Ouvrir la console",
        description: "Connectez-vous à la Twitch Developer Console.",
      },
      {
        title: "Enregistrer l'application",
        description: "Allez dans 'Your Console' > 'Register Your Application'.",
      },
      {
        title: "Remplir le formulaire",
        description: "Remplissez le nom, la catégorie et indiquez une URL de redirection (ex: https://ethone.dev).",
      },
      {
        title: "Récupérer le Client ID",
        description: "Récupérez le Client ID généré.",
      },
      {
        title: "Générer le Client Secret",
        description: "Générez un Client Secret dans l'onglet Secret.",
      },
      {
        title: "Renseigner la chaîne",
        description: "Saisissez le nom (login) de la chaîne à surveiller, ex: Rub10Off.",
      },
    ],
  },
  lastfm: {
    id: "lastfm",
    name: "Last.fm",
    category: "api_key",
    badge: "API KEY",
    description: "Scrobbles, morceaux récents et top artistes Last.fm.",
    developerUrl: "https://www.last.fm/api",
    developerButtonLabel: "API Last.fm",
    docsUrl: "https://www.last.fm/api/account/create",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    secretLabel: "Clé API Last.fm",
    secretPlaceholder: "Votre clé API Last.fm",
    callbackPath: "/",
    steps: [
      {
        title: "Se connecter",
        description: "Connectez-vous à Last.fm.",
      },
      {
        title: "Ouvrir la page API",
        description: "Rendez-vous sur la page API Account.",
      },
      {
        title: "Créer une application API",
        description: "Créez une nouvelle application API.",
      },
      {
        title: "Récupérer la clé API",
        description: "Récupérez la clé API générée.",
      },
      {
        title: "Coller la clé",
        description: "Copiez la clé et collez-la dans le champ ci-dessous.",
      },
    ],
  },
  reddit: {
    id: "reddit",
    name: "Reddit",
    category: "oauth",
    badge: "OAUTH 2.0",
    description: "Activité, posts et subreddits de votre compte Reddit.",
    developerUrl: "https://www.reddit.com/dev/api/",
    developerButtonLabel: "Reddit App Preferences",
    docsUrl: "https://www.reddit.com/prefs/apps",
    requiresClientSecret: true,
    requiresRedirectUri: true,
    idLabel: "Client ID Reddit",
    idPlaceholder: "Votre Client ID Reddit",
    secretLabel: "Client Secret Reddit",
    secretPlaceholder: "Votre Client Secret",
    callbackPath: "/",
    steps: [
      {
        title: "Se connecter",
        description: "Connectez-vous à Reddit.",
      },
      {
        title: "Ouvrir les applications",
        description: "Allez dans Préférences > Applications.",
      },
      {
        title: "Créer une application",
        description: "Cliquez sur 'Create another app...'.",
      },
      {
        title: "Configurer l'application",
        description: "Choisissez 'web app' et donnez un nom à l'application.",
      },
      {
        title: "Ajouter l'URL de redirection",
        description: "Dans les paramètres de l'application, ajoutez l'URL de redirection suivante :",
        copyValueType: "callback",
      },
      {
        title: "Récupérer les identifiants",
        description: "Récupérez le Client ID (sous le nom) et le Client Secret.",
      },
    ],
  },
  bluesky: {
    id: "bluesky",
    name: "Bluesky",
    category: "webhook",
    badge: "WEBHOOK",
    description: "Fil Bluesky et publications du compte configuré.",
    developerUrl: "https://docs.bsky.app/",
    developerButtonLabel: "Documentation Bluesky",
    docsUrl: "https://bsky.app/settings/app-passwords",
    requiresClientSecret: false,
    requiresRedirectUri: false,
    callbackPath: "/",
    steps: [
      {
        title: "Se connecter",
        description: "Connectez-vous à Bluesky.",
      },
      {
        title: "Ouvrir les mots de passe d'application",
        description: "Allez dans Paramètres > Mots de passe d'application.",
      },
      {
        title: "Créer un mot de passe",
        description: "Cliquez sur 'Add App Password'.",
      },
      {
        title: "Copier le mot de passe",
        description: "Donnez un nom (ex: ETHONE) et copiez le mot de passe généré.",
      },
      {
        title: "Renseigner le compte",
        description: "Collez le handle et le mot de passe dans les champs ci-dessous.",
      },
    ],
  },
  steam: {
    id: "steam",
    name: "Steam",
    category: "api_key",
    badge: "API KEY",
    description: "Jeux, succès, profil et temps de jeu Steam.",
    developerUrl: "https://steamcommunity.com/dev",
    developerButtonLabel: "Steam Web API Key",
    docsUrl: "https://steamcommunity.com/dev/apikey",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    secretLabel: "Clé API Steam",
    secretPlaceholder: "Votre clé Steam",
    callbackPath: "/",
    steps: [
      {
        title: "Se connecter",
        description: "Connectez-vous à Steam avec votre compte.",
      },
      {
        title: "Ouvrir la page de clé API",
        description: "Rendez-vous sur la page Steam Web API Key.",
      },
      {
        title: "Renseigner un domaine",
        description: "Entrez un nom de domaine (ex: localhost).",
      },
      {
        title: "Récupérer la clé",
        description: "Acceptez et copiez la clé API générée.",
      },
    ],
  },
  riot: {
    id: "riot",
    name: "Riot Games",
    category: "api_key",
    badge: "API KEY",
    description: "Stats Valorant, League of Legends et TFT du joueur.",
    developerUrl: "https://developer.riotgames.com/",
    developerButtonLabel: "Riot Games Developers",
    docsUrl: "https://developer.riotgames.com/docs/lol",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    secretLabel: "Clé API Henrik",
    secretPlaceholder: "Votre clé API Henrik",
    callbackPath: "/",
    steps: [
      {
        title: "Renseigner le compte Riot",
        description: "Saisissez le nom et le tag du joueur (ex: Player#EUW).",
      },
      {
        title: "Obtenir une clé API Henrik",
        description: "Rendez-vous sur henrikdev.xyz et générez une clé API pour Valorant.",
      },
      {
        title: "Obtenir une clé API Riot (optionnel)",
        description: "Pour LoL / TFT, créez une clé API Riot Games si nécessaire.",
      },
      {
        title: "Coller les clés",
        description: "Collez les clés API dans les champs ci-dessous.",
      },
    ],
  },
  minecraft: {
    id: "minecraft",
    name: "Minecraft",
    category: "webhook",
    badge: "WEBHOOK",
    description: "Profil et statistiques du joueur Minecraft.",
    developerUrl: "https://learn.microsoft.com/minecraft/creator/",
    developerButtonLabel: "Minecraft Creator Docs",
    docsUrl: "https://learn.microsoft.com/minecraft/creator/documents/",
    requiresClientSecret: false,
    requiresRedirectUri: false,
    callbackPath: "/",
    steps: [
      {
        title: "Récupérer le pseudo",
        description: "Ouvrez le launcher Minecraft et récupérez le nom d'utilisateur Java Edition.",
      },
      {
        title: "Saisir le pseudo",
        description: "Collez le pseudo dans le champ ci-dessous.",
      },
    ],
  },
  "tracker-gg": {
    id: "tracker-gg",
    name: "Tracker.gg",
    category: "webhook",
    badge: "RESTRICTED",
    description: "Profil et matchs Apex Legends via Tracker.gg.",
    developerUrl: "https://tracker.gg/developers",
    developerButtonLabel: "Tracker.gg Developers",
    docsUrl: "https://tracker.gg/developers",
    requiresClientSecret: false,
    requiresRedirectUri: false,
    callbackPath: "/",
    steps: [
      {
        title: "Créer un compte",
        description: "Inscrivez-vous sur tracker.gg.",
      },
      {
        title: "Obtenir une clé API",
        description: "Depuis le portail développeur, générez une clé API Tracker.gg.",
      },
      {
        title: "Renseigner l'identifiant Apex",
        description: "Saisissez la plateforme (origin, xbl, psn) et l'identifiant Apex du joueur.",
      },
      {
        title: "Coller la clé",
        description: "Collez la clé API dans le champ ci-dessous.",
      },
    ],
  },
  "google-calendar": {
    id: "google-calendar",
    name: "Google Calendar",
    category: "oauth",
    badge: "OAUTH 2.0",
    description: "Agenda et prochains événements Google Calendar.",
    developerUrl: "https://developers.google.com/workspace/calendar/api",
    developerButtonLabel: "Google Cloud Console",
    docsUrl: "https://console.cloud.google.com/apis/credentials",
    requiresClientSecret: false,
    requiresRedirectUri: true,
    idLabel: "Client ID Google Cloud",
    idPlaceholder: "Votre Client ID Google Cloud",
    callbackPath: "/",
    steps: [
      {
        title: "Ouvrir Google Cloud Console",
        description: "Rendez-vous sur Google Cloud Console.",
      },
      {
        title: "Créer un projet",
        description: "Créez un nouveau projet Google Cloud ou sélectionnez-en un existant.",
      },
      {
        title: "Activer l'API Google Calendar",
        description: "Activez l'API Google Calendar.",
      },
      {
        title: "Créer un ID client OAuth",
        description: "Dans Identifiants, cliquez sur 'Créer des identifiants' > 'ID client OAuth'.",
      },
      {
        title: "Configurer l'écran de consentement",
        description: "Configurez l'écran de consentement si vous y êtes invité.",
      },
      {
        title: "Récupérer le Client ID",
        description: "Récupérez le Client ID et ajoutez l'URL de redirection fournie :",
        copyValueType: "callback",
      },
    ],
  },
  "google-drive": {
    id: "google-drive",
    name: "Google Drive",
    category: "oauth",
    badge: "OAUTH 2.0",
    description: "Fichiers, dossiers et activité récente Google Drive.",
    developerUrl: "https://developers.google.com/drive/api/guides/about-sdk",
    developerButtonLabel: "Google Cloud Console",
    docsUrl: "https://console.cloud.google.com/apis/credentials",
    requiresClientSecret: false,
    requiresRedirectUri: true,
    idLabel: "Client ID Google Cloud",
    idPlaceholder: "Votre Client ID Google Cloud",
    callbackPath: "/",
    steps: [
      {
        title: "Ouvrir Google Cloud Console",
        description: "Rendez-vous sur Google Cloud Console.",
      },
      {
        title: "Créer un projet",
        description: "Créez un nouveau projet Google Cloud ou sélectionnez-en un existant.",
      },
      {
        title: "Activer l'API Google Drive",
        description: "Activez l'API Google Drive.",
      },
      {
        title: "Créer un ID client OAuth",
        description: "Dans Identifiants, cliquez sur 'Créer des identifiants' > 'ID client OAuth'.",
      },
      {
        title: "Configurer l'écran de consentement",
        description: "Configurez l'écran de consentement si vous y êtes invité.",
      },
      {
        title: "Récupérer le Client ID",
        description: "Récupérez le Client ID et ajoutez l'URL de redirection fournie :",
        copyValueType: "callback",
      },
    ],
  },
  clickup: {
    id: "clickup",
    name: "ClickUp",
    category: "api_key",
    badge: "API KEY",
    description: "Tâches, espaces et listes ClickUp.",
    developerUrl: "https://developer.clickup.com/",
    developerButtonLabel: "Paramètres API ClickUp",
    docsUrl: "https://app.clickup.com/settings/apps",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    secretLabel: "Token personnel ClickUp",
    secretPlaceholder: "pk_...",
    callbackPath: "/",
    steps: [
      {
        title: "Ouvrir les paramètres API",
        description: "Rendez-vous dans les paramètres de votre compte ClickUp.",
      },
      {
        title: "Générer un token",
        description: "Dans Integrations > API, créez un token personnel (Personal Token).",
      },
      {
        title: "Coller le token",
        description: "Copiez le token et collez-le dans le champ ci-dessous.",
      },
    ],
  },
  jira: {
    id: "jira",
    name: "Jira",
    category: "api_key",
    badge: "API KEY",
    description: "Tickets, tableaux et projets Jira.",
    developerUrl: "https://developer.atlassian.com/cloud/jira/platform/",
    developerButtonLabel: "Console Atlassian",
    docsUrl: "https://id.atlassian.com/manage-profile/security/api-tokens",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    idLabel: "Domaine",
    idPlaceholder: "mondomaine.atlassian.net",
    secretLabel: "Token API Jira",
    secretPlaceholder: "Votre token API Jira",
    callbackPath: "/",
    steps: [
      {
        title: "Renseigner le domaine et l'email",
        description: "Saisissez le domaine Atlassian (ex: mondomaine.atlassian.net) et l'email du compte.",
      },
      {
        title: "Générer un token API",
        description: "Rendez-vous sur votre profil Atlassian > Sécurité > Tokens API et générez un token.",
      },
      {
        title: "Coller le token",
        description: "Copiez le token API et collez-le dans le champ ci-dessous.",
      },
    ],
  },
  email: {
    id: "email",
    name: "Email",
    category: "oauth",
    badge: "OAUTH 2.0",
    description: "Accès aux comptes mail via IMAP/SMTP.",
    developerUrl: "https://developers.google.com/gmail/api",
    developerButtonLabel: "Google Cloud Console",
    docsUrl: "https://console.cloud.google.com/apis/credentials",
    requiresClientSecret: true,
    requiresRedirectUri: true,
    idLabel: "Client ID Email",
    idPlaceholder: "Votre Client ID",
    secretLabel: "Client Secret Email",
    secretPlaceholder: "Votre Client Secret",
    callbackPath: "/",
    steps: [
      {
        title: "Ouvrir Google Cloud Console",
        description: "Rendez-vous sur Google Cloud Console et créez un projet.",
      },
      {
        title: "Activer l'API Gmail",
        description: "Activez l'API Gmail pour IMAP/SMTP.",
      },
      {
        title: "Créer des identifiants OAuth",
        description: "Dans Identifiants, créez un ID client OAuth de type application web.",
      },
      {
        title: "Ajouter l'URL de redirection",
        description: "Collez l'URL de redirection suivante dans les URIs autorisées :",
        copyValueType: "callback",
      },
      {
        title: "Récupérer le Client ID",
        description: "Copiez le Client ID et le Client Secret, puis connectez-vous.",
      },
    ],
  },
  rss: {
    id: "rss",
    name: "RSS",
    category: "webhook",
    badge: "WEBHOOK",
    description: "Suivi d'un flux RSS/Atom.",
    developerUrl: "https://www.rssboard.org/rss-specification",
    developerButtonLabel: "Spécification RSS",
    requiresClientSecret: false,
    requiresRedirectUri: false,
    callbackPath: "/",
    steps: [
      {
        title: "Récupérer l'URL du flux",
        description: "Récupérez l'URL du flux RSS ou Atom.",
      },
      {
        title: "Vérifier l'accès public",
        description: "Assurez-vous qu'elle est accessible publiquement.",
      },
      {
        title: "Coller l'URL",
        description: "Collez l'URL dans le champ ci-dessus.",
      },
    ],
  },
  weather: {
    id: "weather",
    name: "Météo",
    category: "webhook",
    badge: "WEBHOOK",
    description: "Météo actuelle et prévisions pour une ville.",
    developerUrl: "https://open-meteo.com/en/docs",
    developerButtonLabel: "Open-Meteo Docs",
    requiresClientSecret: false,
    requiresRedirectUri: false,
    callbackPath: "/",
    steps: [
      {
        title: "Aucune clé requise",
        description: "Open-Meteo est gratuit, aucune clé n'est nécessaire.",
      },
      {
        title: "Saisir une ville",
        description: "Entrez simplement une ville dans le champ ci-dessus.",
      },
    ],
  },
  gitlab: {
    id: "gitlab",
    name: "GitLab",
    category: "api_key",
    badge: "API KEY",
    description: "Dépôts, issues et projets GitLab.",
    developerUrl: "https://docs.gitlab.com/integration/oauth_provider/",
    developerButtonLabel: "Paramètres d'accès GitLab",
    docsUrl: "https://gitlab.com/-/profile/personal_access_tokens",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    secretLabel: "Token personnel GitLab",
    secretPlaceholder: "glpat-...",
    callbackPath: "/",
    steps: [
      {
        title: "Ouvrir les paramètres d'accès",
        description: "Rendez-vous dans GitLab > Préférences > Access Tokens.",
      },
      {
        title: "Créer un token personnel",
        description: "Créez un token personnel avec les scopes read_user et read_api.",
      },
      {
        title: "Coller le token",
        description: "Copiez le token généré et collez-le dans le champ ci-dessous.",
      },
    ],
  },
  obsidian: {
    id: "obsidian",
    name: "Obsidian",
    category: "api_key",
    badge: "API KEY",
    description: "Coffres, notes et contenu Obsidian.",
    developerUrl: "https://docs.obsidian.md/Plugins/Getting+started/Build+a+plugin",
    developerButtonLabel: "Documentation Obsidian",
    docsUrl: "https://github.com/coddingtonbear/obsidian-local-rest-api",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    idLabel: "URL API locale",
    idPlaceholder: "http://localhost:27123",
    secretLabel: "Token Obsidian",
    secretPlaceholder: "Token Obsidian",
    callbackPath: "/",
    steps: [
      {
        title: "Activer le plugin Local REST API",
        description: "Dans Obsidian, activez le plugin 'Local REST API' dans les paramètres communautaires.",
      },
      {
        title: "Récupérer l'URL locale",
        description: "Notez l'URL locale de l'API (par défaut http://localhost:27123).",
      },
      {
        title: "Générer un token",
        description: "Dans les paramètres du plugin, générez un token d'accès.",
      },
      {
        title: "Coller les informations",
        description: "Collez l'URL et le token dans les champs ci-dessous.",
      },
    ],
  },
  vscode: {
    id: "vscode",
    name: "VS Code",
    category: "api_key",
    badge: "API KEY",
    description: "Activité, extensions et sessions VS Code.",
    developerUrl: "https://code.visualstudio.com/api",
    developerButtonLabel: "Documentation VS Code",
    docsUrl: "https://code.visualstudio.com/docs/remote/vscode-server",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    idLabel: "URL VS Code Server / locale",
    idPlaceholder: "http://localhost:8080",
    secretLabel: "Token (optionnel)",
    secretPlaceholder: "Token VS Code",
    callbackPath: "/",
    steps: [
      {
        title: "Lancer VS Code Server",
        description: "Installez et lancez VS Code Server ou l'extension 'code-server'.",
      },
      {
        title: "Récupérer l'URL",
        description: "Notez l'URL du serveur (ex: http://localhost:8080).",
      },
      {
        title: "Créer un token (optionnel)",
        description: "Créez un token d'accès si votre serveur en nécessite un.",
      },
      {
        title: "Coller les informations",
        description: "Collez l'URL et le token dans les champs ci-dessous.",
      },
    ],
  },
  fitbit: {
    id: "fitbit",
    name: "Fitbit",
    category: "api_key",
    badge: "API KEY",
    description: "Activité, objectifs et santé Fitbit.",
    developerUrl: "https://dev.fitbit.com/build/reference/web-api/",
    developerButtonLabel: "Fitbit App Registration",
    docsUrl: "https://dev.fitbit.com/apps",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    secretLabel: "Token Fitbit",
    secretPlaceholder: "eyJ...",
    callbackPath: "/",
    steps: [
      {
        title: "Créer une application Fitbit",
        description: "Connectez-vous au Fitbit App Registration et créez une nouvelle application.",
      },
      {
        title: "Générer un token",
        description: "Récupérez un token d'accès OAuth ou un token API dans les paramètres.",
      },
      {
        title: "Coller le token",
        description: "Collez le token dans le champ ci-dessous.",
      },
    ],
  },
  "lm-studio": {
    id: "lm-studio",
    name: "LM Studio",
    category: "webhook",
    badge: "LOCAL",
    description: "Exécution de modèles locaux via LM Studio.",
    developerUrl: "https://lmstudio.ai/docs/developer",
    developerButtonLabel: "Documentation LM Studio",
    docsUrl: "https://lmstudio.ai/docs/developer",
    requiresClientSecret: false,
    requiresRedirectUri: false,
    callbackPath: "/",
    steps: [
      {
        title: "Lancer LM Studio",
        description: "Lancez LM Studio sur votre machine.",
      },
      {
        title: "Activer le serveur",
        description: "Activez le serveur local (Developer > Server).",
      },
      {
        title: "Noter le port",
        description: "Notez le port utilisé (par défaut 1234).",
      },
      {
        title: "Coller l'URL",
        description: "Collez l'URL dans le champ ci-dessus.",
      },
    ],
  },
  ollama: {
    id: "ollama",
    name: "Ollama",
    category: "webhook",
    badge: "LOCAL",
    description: "Exécution de modèles locaux via Ollama.",
    developerUrl: "https://docs.ollama.com/api",
    developerButtonLabel: "Documentation Ollama",
    docsUrl: "https://docs.ollama.com/api",
    requiresClientSecret: false,
    requiresRedirectUri: false,
    callbackPath: "/",
    steps: [
      {
        title: "Installer et lancer Ollama",
        description: "Installez et lancez Ollama localement.",
      },
      {
        title: "Démarrer le serveur",
        description: "Assurez-vous que le serveur est démarré.",
      },
      {
        title: "Noter le port",
        description: "Notez le port par défaut 11434.",
      },
      {
        title: "Coller l'URL",
        description: "Collez l'URL et le nom du modèle dans les champs ci-dessus.",
      },
    ],
  },
  openai: {
    id: "openai",
    name: "OpenAI",
    category: "api_key",
    badge: "API KEY",
    description: "Modèles OpenAI et exécutions via un relais sécurisé.",
    developerUrl: "https://platform.openai.com/docs/",
    developerButtonLabel: "OpenAI API Keys",
    docsUrl: "https://platform.openai.com/api-keys",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    secretLabel: "Clé API OpenAI",
    secretPlaceholder: "sk-...",
    callbackPath: "/",
    steps: [
      {
        title: "Se connecter",
        description: "Connectez-vous à OpenAI.",
      },
      {
        title: "Ouvrir API Keys",
        description: "Allez dans la section API Keys.",
      },
      {
        title: "Créer une clé",
        description: "Cliquez sur 'Create new secret key'.",
      },
      {
        title: "Copier la clé",
        description: "Donnez un nom et copiez la clé (affichée une seule fois).",
      },
    ],
  },
  anthropic: {
    id: "anthropic",
    name: "Anthropic",
    category: "api_key",
    badge: "API KEY",
    description: "Modèles Anthropic Claude et exécutions.",
    developerUrl: "https://docs.anthropic.com/",
    developerButtonLabel: "Console Anthropic",
    docsUrl: "https://console.anthropic.com/settings/keys",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    secretLabel: "Clé API Anthropic",
    secretPlaceholder: "Votre clé API Anthropic",
    callbackPath: "/",
    steps: [
      {
        title: "Se connecter",
        description: "Connectez-vous à la console Anthropic.",
      },
      {
        title: "Ouvrir API Keys",
        description: "Allez dans Settings > API Keys.",
      },
      {
        title: "Créer une clé",
        description: "Créez une nouvelle clé.",
      },
      {
        title: "Copier la clé",
        description: "Copiez la clé et collez-la dans le champ ci-dessous.",
      },
    ],
  },
  gemini: {
    id: "gemini",
    name: "Gemini",
    category: "api_key",
    badge: "API KEY",
    description: "Modèles Google Gemini et exécutions.",
    developerUrl: "https://ai.google.dev/gemini-api/docs",
    developerButtonLabel: "Google AI Studio",
    docsUrl: "https://aistudio.google.com/app/apikey",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    secretLabel: "Clé API Gemini",
    secretPlaceholder: "Votre clé API Google AI",
    callbackPath: "/",
    steps: [
      {
        title: "Ouvrir Google AI Studio",
        description: "Rendez-vous sur Google AI Studio.",
      },
      {
        title: "Se connecter",
        description: "Connectez-vous avec un compte Google.",
      },
      {
        title: "Obtenir une clé API",
        description: "Allez dans 'Get API key'.",
      },
      {
        title: "Copier la clé",
        description: "Créez une clé API et copiez-la.",
      },
    ],
  },
  groq: {
    id: "groq",
    name: "Groq",
    category: "api_key",
    badge: "API KEY",
    description: "API d'inférence et modèles Groq.",
    developerUrl: "https://console.groq.com/docs",
    developerButtonLabel: "Console Groq",
    docsUrl: "https://console.groq.com/keys",
    requiresClientSecret: true,
    requiresRedirectUri: false,
    secretLabel: "Clé API Groq",
    secretPlaceholder: "gsk_...",
    callbackPath: "/",
    steps: [
      {
        title: "Se connecter",
        description: "Connectez-vous à la Groq Console.",
      },
      {
        title: "Ouvrir API Keys",
        description: "Allez dans la section API Keys.",
      },
      {
        title: "Créer une clé",
        description: "Créez une nouvelle clé.",
      },
      {
        title: "Copier la clé",
        description: "Copiez la clé et collez-la dans le champ ci-dessous.",
      },
    ],
  },
};

export function getIntegrationConfig(id: string): IntegrationConfig | undefined {
  return INTEGRATIONS_CONFIG[id];
}
