"use client";

import {
  Home,
  NotebookPen,
  CircleCheck,
  CalendarDays,
  Folder,
  Receipt,
  Activity,
  ScanSearch,
  ShieldCheck,
  History,
  Sunset,
  Flame,
  Plug,
  Blocks,
  LayoutGrid,
  Workflow,
  Brain,
  Timer,
  Users,
  Mail,
  Settings,
  Monitor,
  Menu,
  User,
  Search,
  Command,
  LogOut,
  Sparkles,
  ChevronDown,
  ChevronUp,
  X,
  Maximize2,
  Minimize2,
  Music,
  MessageSquare,
  Code2,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Heart,
  HeartOff,
  GripHorizontal,
  Radio,
  Disc3,
  CloudSun,
  LoaderPinwheel,
  Pin,
  PinOff,
  MapPin,
  Palette,
  Type,
  Gauge,
  Volume2,
  Bell,
  Shield,
  Globe,
  Dock,
  ArrowRight,
  Minus,
  Sun,
  Moon,
  CirclePlus,
  StickyNote,
  AppWindow,
  ChevronLeft,
  ChevronRight,
  Trash2,
  FileEdit,
  KeyRound,
  Lock,
  RotateCcw,
  RefreshCw,
  Share2,
  Gamepad2,
  Swords,
  Layers,
  Database,
  Wifi,
  MoonStar,
  Gem,
  Layers3,
  Smartphone,
  WifiOff,
  CircleCheckBig,
  Expand,
  Shrink,
  Zap,
  AlertCircle,
  Send,
  Inbox,
  Archive,
  AlertTriangle,
  Ghost,
  Coffee,
  Armchair,
  Trophy,
  Quote,
  Unlink,
  Eraser,
  Strikethrough,
  Text,
  HardDrive,
  ExternalLink,
  ArrowUp,
  ArrowDown,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudFog,
  CloudMoon,
  Snowflake,
  Wind,
  Droplets,
  Thermometer,
  Umbrella,
  Sunrise,
  Leaf,
  Navigation,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  List,
  ListOrdered,
  Image,
  Check,
  CalendarPlus,
  FolderPlus,
  UserRound,
  Settings2,
  MoreHorizontal,
  Trees,
  TreePine,
  TreeDeciduous,
  Accessibility,
  AudioLines,
  BatteryCharging,
  Bike,
  BookOpen,
  BookmarkCheck,
  Bot,
  Box,
  BrainCircuit,
  Briefcase,
  Building2,
  CalendarCheck2,
  CalendarClock,
  Car,
  CheckSquare,
  Circle,
  Clapperboard,
  ClipboardCheck,
  Clock,
  CloudCog,
  Construction,
  Copy,
  CopyPlus,
  CornerDownLeft,
  Cpu,
  CreditCard,
  GripVertical,
  Download,
  Dumbbell,
  Eye,
  EyeOff,
  File,
  FilePlus2,
  FileText,
  Film,
  FlipHorizontal,
  Fuel,
  GitFork,
  GitBranch,
  HeartPulse,
  Info,
  Keyboard,
  Languages,
  LayoutDashboard,
  Library,
  Link,
  Link2,
  ListCollapse,
  ListPlus,
  ListTodo,
  Loader2,
  MailPlus,
  MessageCircle,
  MessagesSquare,
  MinusCircle,
  MonitorCog,
  Music2,
  NotebookTabs,
  NotepadText,
  Package,
  PanelLeft,
  PanelTop,
  PanelRight,
  PenTool,
  Pencil,
  PlusCircle,
  RotateCw,
  Rows3,
  Rss,
  Save,
  SearchX,
  Server,
  ServerCog,
  ShieldAlert,
  Shirt,
  SlidersHorizontal,
  Square,
  Star,
  Tag,
  Target,
  Terminal,
  Train,
  TriangleAlert,
  Tv,
  Unplug,
  Upload,
  UploadCloud,
  Video,
  VolumeX,
  Wand2,
  AudioWaveform,
  Waves,
  TrendingUp,
  BarChart3,
  type LucideIcon,
} from "lucide-react";

const LUCIDE_ICON_MAP: Record<string, LucideIcon> = {
  home: Home,
  house: Home,
  notes: NotebookPen,
  note: StickyNote,
  tasks: CircleCheck,
  calendar: CalendarDays,
  "calendar-days": CalendarDays,
  "calendar-check-2": CalendarCheck2,
  "calendar-clock": CalendarClock,
  "calendar-plus": CalendarPlus,
  files: Folder,
  folder: Folder,
  "folder-plus": FolderPlus,
  file: File,
  "file-text": FileText,
  "file-plus-2": FilePlus2,
  "file-edit": FileEdit,
  bills: Receipt,
  receipt: Receipt,
  activity: Activity,
  "scan-search": ScanSearch,
  "shield-check": ShieldCheck,
  "shield-x": ShieldAlert,
  shield: Shield,
  history: History,
  sunset: Sunset,
  interactions: Flame,
  flame: Flame,
  connections: Plug,
  plug: Plug,
  unplug: Unplug,
  plugins: Blocks,
  blocks: Blocks,
  spaces: LayoutGrid,
  layoutGrid: LayoutGrid,
  "layout-grid": LayoutGrid,
  "layout-dashboard": LayoutDashboard,
  flows: Workflow,
  workflow: Workflow,
  brain: Brain,
  "brain-circuit": BrainCircuit,
  focus: Timer,
  timer: Timer,
  clock: Clock,
  team: Users,
  users: Users,
  mail: Mail,
  "mail-plus": MailPlus,
  "envelope-simple": Mail,
  settings: Settings,
  "settings-2": Settings2,
  "gear-six": Settings,
  system: Monitor,
  monitor: Monitor,
  "monitor-cog": MonitorCog,
  server: Server,
  "server-cog": ServerCog,
  cpu: Cpu,
  microchip: Cpu,
  menu: Menu,
  user: User,
  "user-round": UserRound,
  search: Search,
  "search-x": SearchX,
  "magnifying-glass": Search,
  command: Command,
  logout: LogOut,
  "sign-out": LogOut,
  "log-out": LogOut,
  sparkles: Sparkles,
  "wand-sparkles": Wand2,
  chevronDown: ChevronDown,
  "chevron-down": ChevronDown,
  "caret-down": ChevronDown,
  chevronUp: ChevronUp,
  "chevron-up": ChevronUp,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "caret-right": ChevronRight,
  close: X,
  x: X,
  maximize: Maximize2,
  "maximize-2": Maximize2,
  minimize: Minimize2,
  "minimize-2": Minimize2,
  expand: Expand,
  shrink: Shrink,
  music: Music,
  "music-2": Music2,
  discord: MessageSquare,
  "message-square": MessageSquare,
  "message-circle": MessageCircle,
  "messages-square": MessagesSquare,
  code: Code2,
  "code-2": Code2,
  play: Play,
  pause: Pause,
  stop: Square,
  skipBack: SkipBack,
  "skip-back": SkipBack,
  skipForward: SkipForward,
  "skip-forward": SkipForward,
  heart: Heart,
  "heart-pulse": HeartPulse,
  heartOff: HeartOff,
  "heart-off": HeartOff,
  grip: GripHorizontal,
  "grip-horizontal": GripHorizontal,
  "dots-six-vertical": GripVertical,
  radio: Radio,
  disc: Disc3,
  cloudSun: CloudSun,
  "cloud-sun": CloudSun,
  loader: LoaderPinwheel,
  "loader-2": Loader2,
  "loader-circle": Loader2,
  pin: Pin,
  pinOff: PinOff,
  mapPin: MapPin,
  "map-pin": MapPin,
  palette: Palette,
  type: Type,
  gauge: Gauge,
  volume: Volume2,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  "speaker-high": Volume2,
  bell: Bell,
  globe: Globe,
  planet: Globe,
  dock: Dock,
  arrowRight: ArrowRight,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "arrow-clockwise": RotateCw,
  "arrows-clockwise": RefreshCw,
  arrowsClockwise: RefreshCw,
  "rotate-cw": RotateCw,
  "rotate-ccw": RotateCcw,
  "refresh-cw": RefreshCw,
  "arrow-square-out": ExternalLink,
  "external-link": ExternalLink,
  minus: Minus,
  "minus-circle": MinusCircle,
  sun: Sun,
  moon: Moon,
  plus: CirclePlus,
  "plus-circle": PlusCircle,
  stickyNote: StickyNote,
  appWindow: AppWindow,
  "app-window": AppWindow,
  "trash-2": Trash2,
  trash: Trash2,
  "key-round": KeyRound,
  lock: Lock,
  "share-2": Share2,
  "share-network": Share2,
  "gamepad-2": Gamepad2,
  swords: Swords,
  layers: Layers,
  "layers-3": Layers3,
  database: Database,
  wifi: Wifi,
  "wifi-off": WifiOff,
  "moon-star": MoonStar,
  gem: Gem,
  smartphone: Smartphone,
  "device-mobile": Smartphone,
  "circle-check": CircleCheck,
  "circle-check-big": CircleCheckBig,
  "check-circle": CircleCheck,
  "check-square": CheckSquare,
  check: Check,
  "notebook-pen": NotebookPen,
  "notebook-tabs": NotebookTabs,
  "notepad-text": NotepadText,
  zap: Zap,
  alert: AlertCircle,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "triangle-alert": TriangleAlert,
  warning: AlertTriangle,
  send: Send,
  inbox: Inbox,
  archive: Archive,
  ghost: Ghost,
  coffee: Coffee,
  armchair: Armchair,
  trophy: Trophy,
  quote: Quote,
  unlink: Unlink,
  "remove-formatting": Eraser,
  strikethrough: Strikethrough,
  text: Text,
  "hard-drive": HardDrive,
  cloud: Cloud,
  cloudRain: CloudRain,
  "cloud-rain": CloudRain,
  cloudSnow: CloudSnow,
  "cloud-snow": CloudSnow,
  cloudLightning: CloudLightning,
  "cloud-lightning": CloudLightning,
  cloudFog: CloudFog,
  "cloud-fog": CloudFog,
  cloudMoon: CloudMoon,
  "cloud-moon": CloudMoon,
  "cloud-cog": CloudCog,
  snowflake: Snowflake,
  wind: Wind,
  droplets: Droplets,
  thermometer: Thermometer,
  umbrella: Umbrella,
  sunrise: Sunrise,
  leaf: Leaf,
  navigation: Navigation,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  "align-left": AlignLeft,
  "align-center": AlignCenter,
  "align-right": AlignRight,
  list: List,
  "list-ordered": ListOrdered,
  "list-collapse": ListCollapse,
  "list-plus": ListPlus,
  "list-todo": ListTodo,
  image: Image,
  "more-horizontal": MoreHorizontal,
  tree: Trees,
  trees: Trees,
  "tree-pine": TreePine,
  "tree-deciduous": TreeDeciduous,
  forest: Trees,
  accessibility: Accessibility,
  "audio-lines": AudioLines,
  "battery-charging": BatteryCharging,
  bike: Bike,
  "book-open": BookOpen,
  "bookmark-check": BookmarkCheck,
  bot: Bot,
  box: Box,
  "briefcase-business": Briefcase,
  buildings: Building2,
  car: Car,
  circle: Circle,
  clapperboard: Clapperboard,
  "clipboard-check": ClipboardCheck,
  construction: Construction,
  copy: Copy,
  "copy-plus": CopyPlus,
  "corner-down-left": CornerDownLeft,
  "credit-card": CreditCard,
  download: Download,
  dumbbell: Dumbbell,
  eye: Eye,
  "eye-off": EyeOff,
  film: Film,
  "flip-horizontal": FlipHorizontal,
  "folder-simple": Folder,
  fuel: Fuel,
  "git-fork": GitFork,
  github: GitBranch,
  info: Info,
  keyboard: Keyboard,
  languages: Languages,
  library: Library,
  link: Link,
  "link-2": Link2,
  package: Package,
  "panel-left": PanelLeft,
  "panel-top": PanelTop,
  "panels-right-bottom": PanelRight,
  "panels-top-left": PanelLeft,
  "pen-tool": PenTool,
  pencil: Pencil,
  rows3: Rows3,
  "rows-3": Rows3,
  rss: Rss,
  save: Save,
  shirt: Shirt,
  "sliders-horizontal": SlidersHorizontal,
  square: Square,
  star: Star,
  steam: Gamepad2,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  train: Train,
  tv: Tv,
  twitch: Tv,
  upload: Upload,
  "upload-cloud": UploadCloud,
  "upload-simple": Upload,
  video: Video,
  waveform: AudioWaveform,
  waves: Waves,
  youtube: Video,
  bluesky: Cloud,
  reddit: MessageSquare,
  "chart-bar": BarChart3,
  "chart-no-axes-column-increasing": TrendingUp,
  "chart-no-axes-combined": TrendingUp,
};

export type { LucideIcon } from "lucide-react";

export function getLucideIcon(name: string): LucideIcon | undefined {
  return LUCIDE_ICON_MAP[name];
}

