"use client";

import {
  Home,
  NotebookPen,
  CircleCheck,
  CalendarDays,
  Folder,
  Receipt,
  Activity,
  ScanSearch,
  ShieldCheck,
  History,
  Sunset,
  Flame,
  Plug,
  Blocks,
  LayoutGrid,
  Workflow,
  Brain,
  Timer,
  Users,
  Mail,
  Settings,
  Monitor,
  Menu,
  User,
  Search,
  Command,
  LogOut,
  Sparkles,
  ChevronDown,
  ChevronUp,
  X,
  Maximize2,
  Minimize2,
  Music,
  MessageSquare,
  Code2,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Heart,
  HeartOff,
  GripHorizontal,
  Radio,
  Disc3,
  CloudSun,
  LoaderPinwheel,
  Pin,
  PinOff,
  MapPin,
  Palette,
  Type,
  Gauge,
  Volume2,
  Bell,
  Shield,
  Globe,
  Dock,
  ArrowRight,
  Minus,
  Sun,
  Moon,
  CirclePlus,
  StickyNote,
  AppWindow,
  ChevronLeft,
  ChevronRight,
  Trash2,
  FileEdit,
  KeyRound,
  Lock,
  RotateCcw,
  RefreshCw,
  Share2,
  Gamepad2,
  Swords,
  Layers,
  Database,
  Wifi,
  MoonStar,
  Gem,
  Layers3,
  Smartphone,
  WifiOff,
  CircleCheckBig,
  Expand,
  Shrink,
  Zap,
  AlertCircle,
  Send,
  Inbox,
  Archive,
  AlertTriangle,
  Ghost,
  Coffee,
  Armchair,
  Trophy,
  Quote,
  Unlink,
  Eraser,
  Strikethrough,
  Text,
  HardDrive,
  ExternalLink,
  ArrowUp,
  ArrowDown,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudFog,
  CloudMoon,
  Snowflake,
  Wind,
  Droplets,
  Thermometer,
  Umbrella,
  Sunrise,
  Leaf,
  Navigation,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  List,
  ListOrdered,
  Image,
  Check,
  CalendarPlus,
  FolderPlus,
  UserRound,
  Settings2,
  MoreHorizontal,
  type LucideIcon,
} from "lucide-react";

const LUCIDE_ICON_MAP: Record<string, LucideIcon> = {
  home: Home,
  notes: NotebookPen,
  tasks: CircleCheck,
  calendar: CalendarDays,
  files: Folder,
  bills: Receipt,
  activity: Activity,
  "scan-search": ScanSearch,
  "shield-check": ShieldCheck,
  history: History,
  sunset: Sunset,
  interactions: Flame,
  connections: Plug,
  plugins: Blocks,
  spaces: LayoutGrid,
  flows: Workflow,
  brain: Brain,
  focus: Timer,
  team: Users,
  mail: Mail,
  settings: Settings,
  system: Monitor,
  menu: Menu,
  user: User,
  search: Search,
  command: Command,
  logout: LogOut,
  sparkles: Sparkles,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  close: X,
  maximize: Maximize2,
  minimize: Minimize2,
  music: Music,
  discord: MessageSquare,
  code: Code2,
  play: Play,
  pause: Pause,
  skipBack: SkipBack,
  skipForward: SkipForward,
  heart: Heart,
  heartOff: HeartOff,
  grip: GripHorizontal,
  radio: Radio,
  disc: Disc3,
  cloudSun: CloudSun,
  loader: LoaderPinwheel,
  pin: Pin,
  pinOff: PinOff,
  mapPin: MapPin,
  palette: Palette,
  type: Type,
  gauge: Gauge,
  volume: Volume2,
  bell: Bell,
  shield: Shield,
  globe: Globe,
  dock: Dock,
  timer: Timer,
  arrowRight: ArrowRight,
  minus: Minus,
  sun: Sun,
  moon: Moon,
  plus: CirclePlus,
  stickyNote: StickyNote,
  appWindow: AppWindow,
  layoutGrid: LayoutGrid,
  workflow: Workflow,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "trash-2": Trash2,
  "file-edit": FileEdit,
  "loader-2": LoaderPinwheel,
  "key-round": KeyRound,
  lock: Lock,
  "rotate-ccw": RotateCcw,
  "refresh-cw": RefreshCw,
  "share-2": Share2,
  "gamepad-2": Gamepad2,
  swords: Swords,
  layers: Layers,
  database: Database,
  wifi: Wifi,
  "moon-star": MoonStar,
  gem: Gem,
  "layers-3": Layers3,
  smartphone: Smartphone,
  "wifi-off": WifiOff,
  "circle-check": CircleCheck,
  "circle-check-big": CircleCheckBig,
  "notebook-pen": NotebookPen,
  "maximize-2": Maximize2,
  expand: Expand,
  shrink: Shrink,
  zap: Zap,
  users: Users,
  alert: AlertCircle,
  x: X,
  send: Send,
  inbox: Inbox,
  archive: Archive,
  "alert-triangle": AlertTriangle,
  "alert-circle": AlertCircle,
  receipt: Receipt,
  ghost: Ghost,
  coffee: Coffee,
  armchair: Armchair,
  trophy: Trophy,
  quote: Quote,
  unlink: Unlink,
  "remove-formatting": Eraser,
  strikethrough: Strikethrough,
  text: Text,
  "hard-drive": HardDrive,
  "external-link": ExternalLink,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  cloud: Cloud,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  cloudLightning: CloudLightning,
  cloudFog: CloudFog,
  cloudMoon: CloudMoon,
  snowflake: Snowflake,
  wind: Wind,
  droplets: Droplets,
  thermometer: Thermometer,
  umbrella: Umbrella,
  sunrise: Sunrise,
  leaf: Leaf,
  navigation: Navigation,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  "align-left": AlignLeft,
  "align-center": AlignCenter,
  "align-right": AlignRight,
  list: List,
  "list-ordered": ListOrdered,
  image: Image,
  check: Check,
  "calendar-plus": CalendarPlus,
  "folder-plus": FolderPlus,
  "user-round": UserRound,
  "settings-2": Settings2,
  "more-horizontal": MoreHorizontal,
};

export type { LucideIcon } from "lucide-react";

export function getLucideIcon(name: string): LucideIcon | undefined {
  return LUCIDE_ICON_MAP[name];
}
