import type { Settings } from "@/lib/settings";

export type Preset = {
  id: string;
  name: string;
  description: string;
  icon: string;
  settings: Partial<Settings>;
};

export const PRESETS: Preset[] = [
  {
    id: "productivity",
    name: "Productivité",
    description: "Clair, structuré, calme.",
    icon: "circle-check-big",
    settings: {
      theme: "night",
      accentColor: "mint",
      customAccent: "#7be5c3",
      backgroundEffect: "gradient",
      densityMode: "comfortable",
      fontFamily: "sans",
      radiusStyle: "rounded",
      dockScale: "normal",
      dockAlign: "center",
      dockGlass: "default",
      dockAutoHide: false,
      dockMagnify: true,
      uiAnimations: "smooth",
      uiGlow: true,
      uiSoundFeedback: true,
      spotlightEnabled: true,
      ambientEffectsEnabled: true,
      interfaceBlurEnabled: true,
    },
  },
  {
    id: "focus",
    name: "Focus",
    description: "Minimum, calme, sans distraction.",
    icon: "focus",
    settings: {
      theme: "focus",
      accentColor: "sky",
      customAccent: "#7dd3fc",
      backgroundEffect: "solid",
      densityMode: "compact",
      fontFamily: "outfit",
      radiusStyle: "soft",
      dockScale: "compact",
      dockAlign: "center",
      dockGlass: "ultra",
      dockAutoHide: true,
      dockMagnify: false,
      uiAnimations: "snappy",
      uiGlow: false,
      uiSoundFeedback: false,
      spotlightEnabled: false,
      ambientEffectsEnabled: false,
      interfaceBlurEnabled: true,
    },
  },
  {
    id: "gaming",
    name: "Gaming",
    description: "Néon, énergie, contraste.",
    icon: "gamepad-2",
    settings: {
      theme: "cyberpunk",
      accentColor: "rose",
      customAccent: "#fb7185",
      backgroundEffect: "nebula",
      densityMode: "compact",
      fontFamily: "mono",
      radiusStyle: "sharp",
      dockScale: "large",
      dockAlign: "stretch",
      dockGlass: "default",
      dockAutoHide: false,
      dockMagnify: true,
      uiAnimations: "smooth",
      uiGlow: true,
      uiSoundFeedback: true,
      spotlightEnabled: true,
      ambientEffectsEnabled: true,
      interfaceBlurEnabled: true,
    },
  },
  {
    id: "creative",
    name: "Créatif",
    description: "Chaleur, espace, inspiration.",
    icon: "sparkles",
    settings: {
      theme: "aurora",
      accentColor: "violet",
      customAccent: "#a78bfa",
      backgroundEffect: "aurora",
      densityMode: "spacious",
      fontFamily: "serif",
      radiusStyle: "soft",
      dockScale: "normal",
      dockAlign: "center",
      dockGlass: "default",
      dockAutoHide: false,
      dockMagnify: true,
      uiAnimations: "smooth",
      uiGlow: true,
      uiSoundFeedback: true,
      spotlightEnabled: true,
      ambientEffectsEnabled: true,
      interfaceBlurEnabled: true,
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Léger, épuré, silencieux.",
    icon: "minimize-2",
    settings: {
      theme: "minimal",
      accentColor: "mint",
      customAccent: "#7be5c3",
      backgroundEffect: "solid",
      densityMode: "spacious",
      fontFamily: "sans",
      radiusStyle: "rounded",
      dockScale: "compact",
      dockAlign: "center",
      dockGlass: "opaque",
      dockAutoHide: true,
      dockMagnify: false,
      uiAnimations: "reduced",
      uiGlow: false,
      uiSoundFeedback: false,
      spotlightEnabled: false,
      ambientEffectsEnabled: false,
      interfaceBlurEnabled: false,
    },
  },
  {
    id: "developer",
    name: "Développement",
    description: "Compact, lisible, technique.",
    icon: "code",
    settings: {
      theme: "obsidian",
      accentColor: "amber",
      customAccent: "#fbbf24",
      backgroundEffect: "mesh",
      densityMode: "compact",
      fontFamily: "mono",
      radiusStyle: "sharp",
      dockScale: "normal",
      dockAlign: "stretch",
      dockGlass: "default",
      dockAutoHide: false,
      dockMagnify: true,
      uiAnimations: "snappy",
      uiGlow: true,
      uiSoundFeedback: true,
      spotlightEnabled: true,
      ambientEffectsEnabled: true,
      interfaceBlurEnabled: true,
    },
  },
];

export function builtInPresetById(id: string): Preset | null {
  return PRESETS.find((p) => p.id === id) || null;
}
