import { Settings } from "./settings";

export type Preset = {
  id: string;
  name: string;
  description: string;
  icon: string;
  settings: Partial<Settings>;
};

export const BUILT_IN_PRESETS: Preset[] = [
  {
    id: "productivity",
    name: "Productivité",
    description: "Clair, structuré, calme.",
    icon: "circle-check-big",
    settings: {
      theme: "night",
      accentColor: "mint",
      customAccent: "#7be5c3",
      aura: "classic",
      densityMode: "comfortable",
      fontFamily: "sans",
      radiusStyle: "rounded",
      dockScale: "normal",
      dockAlign: "center",
      dockGlass: "vitrified",
      dockAutoHide: false,
      dockMagnify: true,
      homeGrid: "4",
      homeHero: "full",
      uiAnimations: "smooth",
      uiGlow: true,
      uiSoundFeedback: true,
      spotlightEnabled: true,
      ambientEffectsEnabled: true,
      interfaceBlurEnabled: true,
    },
  },
  {
    id: "focus",
    name: "Focus",
    description: "Minimum, calme, sans distraction.",
    icon: "focus",
    settings: {
      theme: "night",
      accentColor: "sky",
      customAccent: "#7dd3fc",
      aura: "eclipse",
      densityMode: "compact",
      fontFamily: "outfit",
      radiusStyle: "soft",
      dockScale: "compact",
      dockAlign: "center",
      dockGlass: "ultra-blur",
      dockAutoHide: true,
      dockMagnify: false,
      homeGrid: "2",
      homeHero: "compact",
      uiAnimations: "snappy",
      uiGlow: false,
      uiSoundFeedback: false,
      spotlightEnabled: false,
      ambientEffectsEnabled: false,
      interfaceBlurEnabled: true,
    },
  },
  {
    id: "gaming",
    name: "Gaming",
    description: "Néon, énergie, contraste.",
    icon: "gamepad-2",
    settings: {
      theme: "graphite",
      accentColor: "rose",
      customAccent: "#fb7185",
      aura: "cyberpunk",
      densityMode: "compact",
      fontFamily: "mono",
      radiusStyle: "sharp",
      dockScale: "large",
      dockAlign: "stretch",
      dockGlass: "vitrified",
      dockAutoHide: false,
      dockMagnify: true,
      homeGrid: "4",
      homeHero: "full",
      uiAnimations: "smooth",
      uiGlow: true,
      uiSoundFeedback: true,
      spotlightEnabled: true,
      ambientEffectsEnabled: true,
      interfaceBlurEnabled: true,
    },
  },
  {
    id: "creative",
    name: "Créatif",
    description: "Chaleur, espace, inspiration.",
    icon: "sparkles",
    settings: {
      theme: "night",
      accentColor: "violet",
      customAccent: "#a78bfa",
      aura: "emeraude",
      densityMode: "spacious",
      fontFamily: "serif",
      radiusStyle: "soft",
      dockScale: "normal",
      dockAlign: "center",
      dockGlass: "vitrified",
      dockAutoHide: false,
      dockMagnify: true,
      homeGrid: "3",
      homeHero: "full",
      uiAnimations: "smooth",
      uiGlow: true,
      uiSoundFeedback: true,
      spotlightEnabled: true,
      ambientEffectsEnabled: true,
      interfaceBlurEnabled: true,
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Léger, épuré, silencieux.",
    icon: "minimize-2",
    settings: {
      theme: "graphite",
      accentColor: "mint",
      customAccent: "#7be5c3",
      aura: "minerale",
      densityMode: "spacious",
      fontFamily: "sans",
      radiusStyle: "rounded",
      dockScale: "compact",
      dockAlign: "center",
      dockGlass: "sober",
      dockAutoHide: true,
      dockMagnify: false,
      homeGrid: "2",
      homeHero: "hidden",
      uiAnimations: "reduced",
      uiGlow: false,
      uiSoundFeedback: false,
      spotlightEnabled: false,
      ambientEffectsEnabled: false,
      interfaceBlurEnabled: false,
    },
  },
  {
    id: "developer",
    name: "Développement",
    description: "Compact, lisible, technique.",
    icon: "code",
    settings: {
      theme: "night",
      accentColor: "amber",
      customAccent: "#fbbf24",
      aura: "boreale",
      densityMode: "compact",
      fontFamily: "mono",
      radiusStyle: "sharp",
      dockScale: "normal",
      dockAlign: "stretch",
      dockGlass: "vitrified",
      dockAutoHide: false,
      dockMagnify: true,
      homeGrid: "4",
      homeHero: "compact",
      uiAnimations: "snappy",
      uiGlow: true,
      uiSoundFeedback: true,
      spotlightEnabled: true,
      ambientEffectsEnabled: true,
      interfaceBlurEnabled: true,
    },
  },
];

export const PRESETS = BUILT_IN_PRESETS;

export const PRESET_IDS = BUILT_IN_PRESETS.map((p) => p.id);

export function builtInPresetById(id: string): Preset | null {
  return BUILT_IN_PRESETS.find((p) => p.id === id) || null;
}
