import { type Settings } from "@/lib/settings";

/**
 * Mapping of active settings category to the top-level settings keys that are
 * exposed by the field definitions in `components/settings/SettingsContent.tsx`.
 *
 * Nested field paths (e.g. `brainPermissions.notes`) are collapsed to their
 * top-level `Settings` key so the whole object is restored to its default value.
 */
export const CATEGORY_KEYS: Record<string, (keyof Settings)[]> = {
  general: ["status", "sessionMode", "layoutPreset", "theme", "language"],
  profile: ["status", "sessionMode"],
  appearance: [
    "darkMode",
    "glassEnabled",
    "cardTilt",
    "shadow",
    "fontSize",
    "fontFamily",
    "densityMode",
    "density",
    "radius",
    "radiusStyle",
    "iconRadius",
    "uiGlow",
    "interfaceBlurEnabled",
  ],
  themes: [
    "theme",
    "accentColor",
    "customAccent",
    "wallpaper",
    "aura",
    "backgroundEffect",
    "backgroundSpeed",
    "iconPack",
  ],
  animations: [
    "uiAnimations",
    "reducedMotion",
    "spotlightEnabled",
    "ambientEffectsEnabled",
  ],
  audio: [
    "masterVolume",
    "soundEffects",
    "mediaDucking",
    "soundVolume",
    "soundSpatial",
    "soundVolumes",
    "soundPack",
    "uiSoundFeedback",
    "focusTimerSound",
  ],
  soundscapes: [
    "ambientSound",
    "masterVolume",
    "mediaDucking",
  ],
  notifications: [
    "notifications",
    "pushNotifications",
    "mailNotifications",
    "trackerNotifications",
    "securityAlerts",
    "liveOverlay",
  ],
  "dynamic-island": [
    "dynamicIslandVisible",
  ],
  dock: [
    "dockVisible",
    "dockAutoHide",
    "dockMagnify",
    "dockScale",
    "dockAlign",
    "dockGlass",
    "dockRadius",
    "dockItems",
    "dockPosition",
    "dockFloatingSave",
  ],
  workspace: [
    "layoutPreset",
    "sidebarVisible",
    "homeGrid",
    "homeHero",
    "homeHiddenLiveCards",
    "homeHiddenSections",
    "activityLiveLayout",
    "focusPreset",
    "zenMode",
  ],
  language: ["language"],
  connections: [
    "liveSpotifyClientId",
    "liveYoutubeClientId",
    "liveRedditClientId",
    "liveTrackerRiotName",
    "liveTrackerRiotTag",
    "liveSteamId",
    "liveSteamAppId",
    "liveRssUrl",
    "liveBlueskyHandle",
    "liveJellyfinUrl",
    "liveEmbyUrl",
    "liveLmStudioUrl",
    "liveOllamaUrl",
    "liveObsidianUrl",
    "liveVscodeUrl",
    "liveLastfmUsername",
    "liveTwitchLogin",
    "liveMinecraftUsername",
  ],
  privacy: [
    "presenceShowSignals",
    "brainMemoryCategories",
  ],
  security: [
    "securityAlerts",
  ],
  sync: [
    "liveOverlay",
  ],
  storage: [
    "commandHistory",
  ],
  performance: [
    "performanceMode",
    "lowData",
    "backgroundQuality",
    "haptics",
  ],
  accessibility: [
    "reducedMotion",
    "fontSize",
    "uiGlow",
  ],
  shortcuts: [
    "pinnedCommands",
  ],
  advanced: [
    "densityCustom",
    "haptics",
    "lowData",
    "performanceMode",
    "backgroundQuality",
  ],
  about: [],
};
