/* Extracted from index.html. Preserve global contracts and load order. */
(function(){
  'use strict';
  if(window.__ethoneLeanProductionBoot)return;
  if(window.__ethoneFullI18nFix)return; window.__ethoneFullI18nFix=true;
  const PHRASES={
    "Profile":"Profil","Enter your PIN to continue":"Entrez votre code PIN pour continuer","Unlock":"Déverrouiller","Back to profiles":"Retour aux profils","← Back to profiles":"← Retour aux profils",
    "Select user":"Sélectionner","Who's using?":"Qui utilise ?","Choose your profile to continue":"Choisissez votre profil pour continuer","Manage profiles":"Gérer les profils","Sign out":"Déconnexion","Add profile":"Ajouter profil","New workspace":"Nouvel espace","Personal workspace":"Espace personnel","Create your first ETHONE space to retrieve your dashboard, settings and customizations.":"Crée ton premier espace ETHONE pour retrouver ton dashboard, tes réglages et tes personnalisations.","Create your first ETHONE space to access your dashboard, settings and customizations.":"Crée ton premier espace ETHONE pour accéder à ton dashboard, tes réglages et tes personnalisations.","No profiles":"Aucun profil","no_profiles":"Aucun profil",
    "Personal dashboard":"Dashboard personnel","French":"Français","English":"Anglais","Spanish":"Espagnol","German":"Allemand","Add item":"Ajouter","+ Add":"+ Ajouter","+ Add item":"+ Ajouter","Total Files":"Fichiers","stored items":"éléments stockés","Tasks Done":"Tâches faites","of 0 total":"sur 0 au total","Links Saved":"Liens sauvegardés","bookmarked":"favoris","Time":"Heure","Quick Access":"Accès rapide","+ Pin link":"+ Épingler","No pinned links yet — click + Pin link":"Aucun lien épinglé — cliquez sur + Épingler","Recent items":"Éléments récents","See all →":"Voir tout →","No items yet":"Aucun élément","Upcoming tasks":"Tâches à venir","All →":"Tout →","All done!":"Tout est fait !","Upcoming events":"Événements à venir","Calendar →":"Calendrier →","No events":"Aucun événement","Quick note":"Note rapide","Open →":"Ouvrir →","Activity":"Activité","Recent activity":"Activité récente","Clear":"Vider","Focus du jour":"Focus du jour","No goal for today...":"Pas d'objectif pour aujourd'hui...",
    "Pomodoro":"Pomodoro","History →":"Historique →","Focus":"Focus","Short":"Court","Short break":"Pause courte","Long":"Long","Long break":"Pause longue","Controls":"Contrôles","Stats":"Stats","Weather":"Météo","Loading weather...":"Chargement météo...","Quote":"Citation","Quote of the day":"Citation du jour","Loading...":"Chargement...","Countdown":"Compte à rebours","Set":"Définir","No countdown set":"Aucun compte à rebours",
    "Library":"Bibliothèque","Files & Links":"Fichiers & liens","All":"Tout","Files":"Fichiers","Links":"Liens","Images":"Images","No items yet. Click":"Aucun élément. Cliquez sur","Writing":"Écriture","Notes":"Notes","New note":"Nouvelle note","No note selected":"Aucune note sélectionnée","Select a note from the list or create a new one":"Sélectionnez une note dans la liste ou créez-en une","Auto-saved":"Sauvegardé automatiquement","Delete":"Supprimer","Markdown toolbar":"Barre Markdown","Copy":"Copier","0 chars":"0 caractère","0 words":"0 mot",
    "Productivity":"Productivité","Tasks":"Tâches","Pending":"En cours","Done":"Terminées","High":"Priorité haute","New task":"Nouvelle tâche","To Do":"À faire","0 pending":"0 en cours","Completed":"Terminées","Clear all":"Tout vider","Nothing completed yet":"Rien de terminé pour l'instant","Daily routine":"Routine quotidienne","Habits":"Habitudes","New habit":"Nouvelle habitude","This week":"Cette semaine","No habits yet — add one!":"Aucune habitude — ajoutez-en une !","Streaks":"Séries","Complete habits to build streaks!":"Complétez vos habitudes pour créer une série !","Workflow":"Workflow","New card":"Nouvelle carte","Drop here":"Déposez ici","+ Add card":"+ Ajouter une carte","Schedule":"Planning","Add event":"Ajouter événement","All events":"Tous les événements","Clear past":"Effacer le passé","No events yet":"Aucun événement",
    "Analytics":"Analyse","Statistics":"Statistiques","Present":"Présenter","Top KPIs":"KPIs principaux","Total items":"Total éléments","files & links":"fichiers & liens","Tasks completed":"Tâches terminées","all time":"depuis toujours","Best habit streak":"Meilleure série","days in a row":"jours d'affilée","Pomodoros":"Pomodoros","0h focus":"0h focus","Activity heatmap":"Heatmap d'activité","LAST 6 MONTHS":"6 DERNIERS MOIS","Less":"Moins","More":"Plus","Charts row":"Ligne graphiques","Activity chart":"Graphique d'activité","LAST 7 DAYS":"7 DERNIERS JOURS","Pomodoro chart":"Graphique Pomodoro","Tasks donut":"Répartition tâches","Habits completion":"Habitudes complétées","WEEKLY GOALS":"OBJECTIFS HEBDO","Weekly Goals":"Objectifs hebdo","+ New goal":"+ Nouvel objectif","Progress overview":"Vue de progression",
    "Journal":"Journal","Daily entries with mood tracking":"Entrées quotidiennes avec suivi d'humeur","+ Today's entry":"+ Entrée du jour","Entries":"Entrées","Entry viewer/editor":"Lecteur/éditeur d'entrée","No entry selected":"Aucune entrée sélectionnée","Write today's entry to start your journal":"Écrivez l'entrée du jour pour commencer votre journal","Countdowns":"Comptes à rebours","Count down to your important events":"Suivez le temps restant avant vos événements importants","+ New countdown":"+ Nouveau compte à rebours","No countdowns yet":"Aucun compte à rebours","Add an event to start counting down":"Ajoutez un événement pour commencer","+ Add event":"+ Ajouter un événement",
    "Your stats":"Vos stats","Your Valorant & League of Legends stats in real time":"Vos stats Valorant & League of Legends en temps réel","Not connected":"Non connecté","Connect":"Connecter","Disconnect":"Déconnecter","Region":"Région","Get key ↗":"Obtenir une clé ↗","League of Legends":"League of Legends","Enter your Summoner Name + your free Riot API key":"Entrez votre Summoner Name + votre clé Riot API gratuite","The Riot dev key is free but expires every 24h. Paste yours here.":"La clé développeur Riot est gratuite mais expire toutes les 24h. Collez-la ici.","Compare with Friends":"Comparer avec des amis","Compare your Valorant & Steam stats side by side":"Comparez vos stats Valorant & Steam côte à côte","Add friend":"Ajouter ami","+ Add friend":"+ Ajouter ami","Or pick from dashboard users":"Ou choisissez parmi les utilisateurs du dashboard","Results":"Résultats",
    "Integrations":"Intégrations","Connections":"Connexions","Link your accounts to enrich your dashboard":"Connectez vos comptes pour enrichir votre dashboard","ETHONE AI — Groq API Key":"ETHONE IA — Clé API Groq","ETHONE AI KEY":"CLÉ ETHONE IA","Free key on":"Clé gratuite sur","Clé gratuite sur":"Clé gratuite sur","Key configured":"Clé configurée","Save":"Sauvegarder","Sidebar Widgets":"Widgets de sidebar","Toggle and reorder widgets shown in the sidebar":"Activez et réorganisez les widgets affichés dans la sidebar","Show your status, avatar and activity via Lanyard":"Affiche votre statut, avatar et activité via Lanyard","Sidebar":"Sidebar","Offline":"Hors ligne","Playing":"En jeu","Some badges (Nitro, etc.) cannot be detected automatically — check the ones you have.":"Certains badges (Nitro, etc.) ne peuvent pas être détectés automatiquement — cochez ceux que vous avez.","DISCORD USER ID":"ID UTILISATEUR DISCORD","Enable Developer Mode in Discord → right-click your name → Copy User ID":"Activez le mode développeur dans Discord → clic droit sur votre nom → Copier l'identifiant utilisateur","Show your status, current game and recent activity":"Affiche votre statut, jeu actuel et activité récente","View profile ↗":"Voir le profil ↗","Recent Games":"Jeux récents","Required for level":"Requis pour le niveau","How to get your free key:":"Comment obtenir votre clé gratuite :","Sign in with your Steam account":"Connectez-vous avec votre compte Steam","Click":"Cliquez","Register":"Register","copy the key":"copiez la clé","Key stored locally, never sent anywhere except Steam.":"Clé stockée localement, jamais envoyée ailleurs qu'à Steam.","Spotify — Now Playing":"Spotify — Lecture en cours","Show what you're listening to in the sidebar":"Affiche ce que vous écoutez dans la sidebar","Remove":"Supprimer","Get your widget URL at":"Récupérez l'URL du widget sur","Track up to 3 streamers — shows live ones in sidebar":"Suivez jusqu'à 3 streamers — affiche les lives dans la sidebar","Streamer list":"Liste des streamers","Add streamer":"Ajouter streamer","ADD STREAMER (max 3)":"AJOUTER STREAMER (max 3)","Show your music history and top artists in your sidebar":"Affiche votre historique musical et vos meilleurs artistes dans la sidebar","LAST.FM USERNAME":"NOM D'UTILISATEUR LAST.FM",
    "Configuration":"Configuration","Settings":"Paramètres","Security":"Sécurité","Account":"Compte","Content":"Contenu","XP / Level":"XP / Niveau","Next level: 100 XP":"Niveau suivant : 100 XP","Complete tasks, pomodoros and notes to earn XP":"Terminez des tâches, pomodoros et notes pour gagner de l'XP","Quick stats":"Stats rapides","Identity":"Identité","Display name":"Nom affiché","Bio":"Bio","Social links":"Liens sociaux","Appearance":"Apparence","Avatar":"Avatar","Change avatar":"Changer l'avatar","Accent color":"Couleur d'accent","Custom color":"Couleur personnalisée","Animated background":"Fond animé","Profile banner":"Bannière de profil","Click to upload banner ·":"Cliquez pour importer une bannière ·","Sidebar layout":"Disposition sidebar","Drag to reorder · Toggle to show/hide":"Glissez pour réorganiser · Activez/désactivez l'affichage","Data":"Données","Export JSON":"Exporter JSON","Import JSON":"Importer JSON","Enable notifications":"Activer les notifications","Danger zone":"Zone dangereuse","Reset my data":"Réinitialiser mes données","Profile protection":"Protection du profil","Password protection":"Protection par mot de passe","Lock this profile with a PIN or password":"Verrouille ce profil avec un PIN ou un mot de passe","Type":"Type","PIN (4 digits)":"PIN (4 chiffres)","Password (text)":"Mot de passe (texte)","Set your 4-digit PIN":"Définissez votre PIN à 4 chiffres","Set your password":"Définissez votre mot de passe","Save protection":"Sauvegarder la protection","Protected with a":"Protégé avec un","Remove protection":"Supprimer la protection","Account info":"Infos du compte","Username":"Nom d'utilisateur","Session":"Session",
    "Chats saved":"Chats sauvegardés","Saved chats":"Chats sauvegardés","Powered by Groq":"Propulsé par Groq","History":"Historique","Capabilities":"Capacités","New chat":"Nouveau chat","ETHONE AI has access to your dashboard context":"ETHONE IA a accès au contexte de votre dashboard","Summarize my tasks":"Résumer mes tâches","What should I focus on today?":"Sur quoi me concentrer aujourd'hui ?","Review my habits this week":"Analyser mes habitudes cette semaine","Help me write a note":"Aide-moi à écrire une note","Suggest a Pomodoro schedule":"Suggérer un planning Pomodoro","Ask anything about your dashboard…":"Posez une question sur votre dashboard…","Match Details":"Détails du match","Press ESC to exit":"Appuyez sur Échap pour quitter","Notifications":"Notifications","No notifications":"Aucune notification","navigate":"naviguer","select":"sélectionner","close":"fermer","Personalize ETHONE":"Personnaliser ETHONE","Accent, background and density. Saved locally, without touching Supabase data.":"Accent, arrière-plan et densité. Sauvegardé localement, sans toucher aux données Supabase.","Background":"Arrière-plan","Aurora":"Aurore","Grid":"Grille","Minimal":"Minimal","Compact density":"Densité compacte","Reduce spacing for power users.":"Réduit l'espacement pour les utilisateurs avancés.","Reduced motion":"Animations réduites","Keep transitions calmer.":"Rend les transitions plus calmes.","Close":"Fermer","Actions rapides ETHONE":"Actions rapides ETHONE","Dashboard — revenir à l’accueil":"Dashboard — revenir à l’accueil","Recherche globale / Command palette — Ctrl K":"Recherche globale / Palette de commandes — Ctrl K","Ouvrir la recherche globale":"Ouvrir la recherche globale","Notes — ouvrir tes notes":"Notes — ouvrir vos notes","Tasks — ouvrir tes tâches":"Tâches — ouvrir vos tâches","Personnalisation — thème, accent, background":"Personnalisation — thème, accent, arrière-plan","Ouvrir la personnalisation":"Ouvrir la personnalisation",
    "New weekly goal":"Nouvel objectif hebdo","GOAL":"OBJECTIF","TARGET (optional)":"OBJECTIF CHIFFRÉ (optionnel)","EMOJI":"EMOJI","Cancel":"Annuler","Add goal":"Ajouter objectif","Journal entry":"Entrée de journal","MOOD":"HUMEUR","TITLE (optional)":"TITRE (optionnel)","WRITE":"ÉCRIRE","Save entry":"Sauvegarder l'entrée","New countdown":"Nouveau compte à rebours","EVENT NAME":"NOM DE L'ÉVÉNEMENT","DATE":"DATE","COLOR":"COULEUR","Add":"Ajouter","Link":"Lien","File":"Fichier","Folder":"Dossier","Image":"Image","Name":"Nom","NAME":"NOM","URL (link only)":"URL (lien uniquement)","File upload":"Import fichier","UPLOAD FILE":"IMPORTER UN FICHIER","Click to choose a file, or drag & drop":"Cliquez pour choisir un fichier ou glissez-déposez","Any file type · stored as link":"Tout type de fichier · stocké comme lien","Folder path (folder type)":"Chemin du dossier (type dossier)","FOLDER CONTENTS":"CONTENU DU DOSSIER","Click to choose a folder":"Cliquez pour choisir un dossier","Lists all files inside":"Liste tous les fichiers à l'intérieur","Image upload":"Import image","Click to choose an image":"Cliquez pour choisir une image","NOTES (optional)":"NOTES (optionnel)","New task":"Nouvelle tâche","TASK":"TÂCHE","PRIORITY":"PRIORITÉ","Normal":"Normal","Low":"Basse","DUE DATE":"DATE LIMITE","TAG":"TAG","Add task":"Ajouter tâche"
  };
  const ES={"Connections":"Conexiones","Integrations":"Integraciones","Link your accounts to enrich your dashboard":"Vincula tus cuentas para enriquecer tu dashboard","Settings":"Ajustes","Tasks":"Tareas","Notes":"Notas","Search everything…":"Buscar en todo…","Personalize ETHONE":"Personalizar ETHONE","Accent color":"Color de acento","Background":"Fondo","Compact density":"Densidad compacta","Reduced motion":"Movimiento reducido","Close":"Cerrar","Notifications":"Notificaciones","No notifications":"Sin notificaciones","Add item":"Añadir","Dashboard":"Dashboard","Profile":"Perfil","Security":"Seguridad","Account":"Cuenta","Save":"Guardar","Cancel":"Cancelar","Add":"Añadir","Connect":"Conectar","Disconnect":"Desconectar","Connected":"Conectado","Not connected":"No conectado","Refresh":"Actualizar"};
  const DE={"Connections":"Verbindungen","Integrations":"Integrationen","Link your accounts to enrich your dashboard":"Verbinde deine Konten, um dein Dashboard zu erweitern","Settings":"Einstellungen","Tasks":"Aufgaben","Notes":"Notizen","Search everything…":"Alles suchen…","Personalize ETHONE":"ETHONE personalisieren","Accent color":"Akzentfarbe","Background":"Hintergrund","Compact density":"Kompakte Dichte","Reduced motion":"Reduzierte Bewegung","Close":"Schließen","Notifications":"Benachrichtigungen","No notifications":"Keine Benachrichtigungen","Add item":"Hinzufügen","Dashboard":"Dashboard","Profile":"Profil","Security":"Sicherheit","Account":"Konto","Save":"Speichern","Cancel":"Abbrechen","Add":"Hinzufügen","Connect":"Verbinden","Disconnect":"Trennen","Connected":"Verbunden","Not connected":"Nicht verbunden","Refresh":"Aktualisieren"};
  const LANGS={fr:PHRASES,es:{...PHRASES,...ES},de:{...PHRASES,...DE},en:{}};
  function getLang(){return String(window._lang||localStorage.getItem('nexus_lang')||localStorage.getItem('ethone_lang')||document.documentElement.lang||'fr').slice(0,2).toLowerCase();}
  function clean(s){return String(s||'').replace(/\s+/g,' ').trim();}
  function stripEmoji(s){return clean(String(s||'').replace(/^[\p{Emoji_Presentation}\p{Extended_Pictographic}\s]+/u,''));}
  function tableFor(lang){return LANGS[lang]||LANGS.fr;}
  function translateText(raw,lang){
    const txt=clean(raw); if(!txt)return raw;
    if(lang==='en')return raw;
    const table=tableFor(lang);
    if(table[txt]) return raw.replace(txt,table[txt]);
    const se=stripEmoji(txt); if(se!==txt && table[se]) return raw.replace(se,table[se]);
    return raw;
  }
  function walk(root,lang){
    const skip='script,style,svg,canvas,input,textarea,select,code,kbd,[contenteditable="true"],.ai-message.user,.note-area,.modal-input';
    const walker=document.createTreeWalker(root||document.body,NodeFilter.SHOW_TEXT,{acceptNode(node){
      const p=node.parentElement; if(!p||p.closest(skip))return NodeFilter.FILTER_REJECT;
      const tx=clean(node.nodeValue); if(!tx||!/[A-Za-z]/.test(tx))return NodeFilter.FILTER_REJECT;
      return NodeFilter.FILTER_ACCEPT;
    }});
    const nodes=[]; while(walker.nextNode())nodes.push(walker.currentNode);
    nodes.forEach(n=>{const next=translateText(n.nodeValue,lang); if(next!==n.nodeValue)n.nodeValue=next;});
  }
  function attrs(root,lang){
    const table=tableFor(lang);
    (root||document).querySelectorAll('[placeholder],[title],[aria-label],input[type="button"],input[type="submit"],button[value]').forEach(el=>{
      ['placeholder','title','aria-label','value'].forEach(a=>{ if(!el.hasAttribute(a))return; const v=clean(el.getAttribute(a)); if(!v)return; const nv=table[v]||table[stripEmoji(v)]; if(nv)el.setAttribute(a,nv); });
    });
    const search=document.querySelector('.topbar .search-bar input,#global-search,#cmd-search'); if(search && lang==='fr')search.setAttribute('placeholder','Rechercher…');
    const kbd=document.querySelectorAll('.eh-kbd-hint span'); kbd.forEach(s=>{if(lang==='fr')s.textContent='Ctrl K';});
  }
  function apply(){
    const lang=getLang(); document.documentElement.lang=lang;
    walk(document.body,lang); attrs(document,lang);
    try{ if(window.updateAuthLangBar)window.updateAuthLangBar(); }catch(e){}
  }
  let timer=0; function schedule(){clearTimeout(timer); timer=setTimeout(apply,60);}
  const oldSetLang=window.setLang;
  if(typeof oldSetLang==='function' && !oldSetLang.__fullI18nWrapped){
    window.setLang=function(l){const r=oldSetLang.apply(this,arguments);try{window._lang=l;localStorage.setItem('nexus_lang',l);localStorage.setItem('ethone_lang',l);}catch(e){} setTimeout(apply,30); return r;};
    window.setLang.__fullI18nWrapped=true;
  }
  const oldSwitch=window.switchPage;
  if(typeof oldSwitch==='function' && !oldSwitch.__i18nWrapped){
    window.switchPage=function(){const r=oldSwitch.apply(this,arguments);setTimeout(apply,80);return r;}; window.switchPage.__i18nWrapped=true;
  }
  const oldOpen=window.openModal;
  if(typeof oldOpen==='function' && !oldOpen.__i18nWrapped){
    window.openModal=function(){const r=oldOpen.apply(this,arguments);setTimeout(apply,80);return r;}; window.openModal.__i18nWrapped=true;
  }
  function startI18nRuntime(){
    try{new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true,characterData:true});}catch(e){}
    if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(apply,80),{once:true}); else setTimeout(apply,80);
    setTimeout(apply,500); setTimeout(apply,1500);
  }
  window.ethoneApplyFullTranslations=apply;
  window.ethoneI18nAudit=function(){
    const lang=getLang(); const english=[];
    const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;if(!p||p.closest('script,style,svg,canvas,input,textarea,select'))return NodeFilter.FILTER_REJECT;const tx=clean(n.nodeValue);if(/[A-Za-z]{4,}/.test(tx)&&lang==='fr'&&!/[éèàçùêâîôûëïüÉÈÀÇÙ]/.test(tx))return NodeFilter.FILTER_ACCEPT;return NodeFilter.FILTER_REJECT;}});
    while(walker.nextNode())english.push(clean(walker.currentNode.nodeValue));
    const result=[...new Set(english)];
    window.__ethoneI18nAudit=result;
    try{if(localStorage.getItem('ethone:debug-i18n')==='1'||/[?&]debugI18n=1\b/.test(location.search))console.table(result.slice(0,120));}catch(e){}
    return result;
  };
  if(window.ethoneRunWhenDashboardReady)window.ethoneRunWhenDashboardReady('full-i18n-runtime',startI18nRuntime);else startI18nRuntime();
})();
