import { FullWelcomeConfig } from './welcomeConfig.js';
import { OnboardingFlow } from './onboarding.js';

export interface WelcomeTemplate {
  id: string;
  name: string;
  category: 'Gaming' | 'Community' | 'Creator' | 'Support' | 'Professional' | 'Minimal';
  description: string;
  badge: string;
  previewColor: string;
  config: Partial<FullWelcomeConfig>;
  onboarding?: Partial<OnboardingFlow>;
}

export const PREBUILT_TEMPLATES: WelcomeTemplate[] = [
  {
    id: 'tpl-community',
    name: 'Grande Communauté',
    category: 'Community',
    description: 'Idéal pour les serveurs généralistes avec vérification et choix de salons.',
    badge: 'Populaire',
    previewColor: '#10B981',
    config: {
      welcome: {
        enabled: true,
        channelId: null,
        messageContent: '🎉 Bienvenue {user} sur **{server}** ! Installe-toi confortablement.',
        mentionUser: true,
        sendForBots: false,
        embed: {
          enabled: true,
          title: 'Bienvenue sur {server} !',
          description:
            'Nous sommes heureux de te compter parmi nous ! Prends connaissance des règles et choisis tes rôles.',
          color: '#10B981',
          authorName: '{username} vient de rejoindre la communauté',
          authorIconUrl: null,
          footer: 'Membre #{membercount} • {server}',
          footerIconUrl: null,
          thumbnailUrl: null,
          imageUrl: null,
          showTimestamp: true,
          showThumbnail: true,
          fields: [
            { id: 'f-rules', name: '📜 Règlement', value: 'Prends le temps de lire nos règles.', inline: true },
            { id: 'f-help', name: '❓ Besoin d’aide ?', value: 'Ouvre un ticket ou demande au staff.', inline: true },
          ],
        },
        image: {
          enabled: true,
          template: 'modern',
          titleText: 'BIENVENUE',
          subtitleText: '{username}',
          tagText: 'Membre #{membercount}',
          accentColor: '#10B981',
          customBackgroundUrl: null,
        },
        buttons: [
          { id: 'btn-rules', label: 'Règlement', emoji: '📜', style: 'SECONDARY', action: 'RULES', target: '' },
          { id: 'btn-verify', label: 'Vérifier mon compte', emoji: '✅', style: 'SUCCESS', action: 'VERIFY', target: '' },
        ],
        dm: {
          enabled: false,
          messageContent: 'Bienvenue sur {server} !',
          embed: {
            enabled: true,
            title: 'Bienvenue sur {server} !',
            description: 'N’hésite pas à explorer nos salons communautaires.',
            color: '#10B981',
            authorName: '{server}',
            authorIconUrl: null,
            footer: '{server}',
            footerIconUrl: null,
            thumbnailUrl: null,
            imageUrl: null,
            showTimestamp: true,
            showThumbnail: true,
            fields: [],
          },
          buttons: [],
        },
        conditions: {
          enabled: false,
          minAccountAgeDays: 0,
          requireVerificationBeforeWelcome: false,
          requiredRoleIds: [],
          excludedRoleIds: [],
        },
        autoRoleIds: [],
      },
    },
  },
  {
    id: 'tpl-gaming',
    name: 'Serveur Gaming & Esport',
    category: 'Gaming',
    description: 'Ambiance gaming percutante avec attribution de rôles de jeux et boutons discord.',
    badge: 'Gaming',
    previewColor: '#8B5CF6',
    config: {
      welcome: {
        enabled: true,
        channelId: null,
        messageContent: '🎮 Un nouveau challenger approche ! Bienvenue {user} dans l’arène **{server}**.',
        mentionUser: true,
        sendForBots: false,
        embed: {
          enabled: true,
          title: '⚔️ Nouveau Joueur Détecté !',
          description:
            'Bienvenue {user} ! Choisis tes jeux préférés et rejoins tes coéquipiers dans les vocaux.',
          color: '#8B5CF6',
          authorName: '{username} est prêt à jouer',
          authorIconUrl: null,
          footer: 'Joueur #{membercount} • {server}',
          footerIconUrl: null,
          thumbnailUrl: null,
          imageUrl: null,
          showTimestamp: true,
          showThumbnail: true,
          fields: [
            { id: 'f-voice', name: '🔊 Salons Vocaux', value: 'Rejoins une escouade libre !', inline: true },
            { id: 'f-tournaments', name: '🏆 Tournois', value: 'Événements hebdomadaires organisés.', inline: true },
          ],
        },
        image: {
          enabled: true,
          template: 'gaming',
          titleText: 'GAME ON',
          subtitleText: '{username}',
          tagText: 'Joueur #{membercount}',
          accentColor: '#8B5CF6',
          customBackgroundUrl: null,
        },
        buttons: [
          { id: 'btn-roles', label: 'Choisir mes jeux', emoji: '🎮', style: 'PRIMARY', action: 'ROLE', target: '' },
          { id: 'btn-rules', label: 'Règles du jeu', emoji: '📜', style: 'SECONDARY', action: 'RULES', target: '' },
        ],
        dm: {
          enabled: false,
          messageContent: 'Prépare-toi à jouer sur {server} !',
          embed: {
            enabled: true,
            title: 'Bienvenue dans la Team !',
            description: 'Tous les canaux sont débloqués.',
            color: '#8B5CF6',
            authorName: '{server}',
            authorIconUrl: null,
            footer: '{server}',
            footerIconUrl: null,
            thumbnailUrl: null,
            imageUrl: null,
            showTimestamp: true,
            showThumbnail: true,
            fields: [],
          },
          buttons: [],
        },
        conditions: {
          enabled: false,
          minAccountAgeDays: 0,
          requireVerificationBeforeWelcome: false,
          requiredRoleIds: [],
          excludedRoleIds: [],
        },
        autoRoleIds: [],
      },
    },
  },
  {
    id: 'tpl-support',
    name: 'Support & Helpdesk Pro',
    category: 'Support',
    description: 'Orienté assistance, service client et résolution de tickets rapide.',
    badge: 'Pro',
    previewColor: '#3B82F6',
    config: {
      welcome: {
        enabled: true,
        channelId: null,
        messageContent: '👋 Bonjour {user}, bienvenue sur le centre d’assistance de **{server}**.',
        mentionUser: true,
        sendForBots: false,
        embed: {
          enabled: true,
          title: '🎫 Centre de Support Client',
          description:
            'Bienvenue {user} ! Notre équipe d’assistance est à votre écoute. Ouvrez un ticket si vous avez la moindre question.',
          color: '#3B82F6',
          authorName: 'Assistance {server}',
          authorIconUrl: null,
          footer: 'Support • {server}',
          footerIconUrl: null,
          thumbnailUrl: null,
          imageUrl: null,
          showTimestamp: true,
          showThumbnail: true,
          fields: [
            { id: 'f-faq', name: '📚 Documentation', value: 'Consultez les guides épinglés.', inline: true },
            { id: 'f-hours', name: '⏰ Horaires Staff', value: 'Actif 7j/7 avec réponse rapide.', inline: true },
          ],
        },
        image: {
          enabled: false,
          template: 'minimal',
          titleText: 'SUPPORT',
          subtitleText: '{username}',
          tagText: 'Client #{membercount}',
          accentColor: '#3B82F6',
          customBackgroundUrl: null,
        },
        buttons: [
          { id: 'btn-ticket', label: 'Ouvrir un Ticket', emoji: '🎫', style: 'PRIMARY', action: 'TICKET', target: 'support_general' },
          { id: 'btn-faq', label: 'Centre d’aide', emoji: '🔗', style: 'LINK', action: 'URL', target: 'https://discord.com' },
        ],
        dm: {
          enabled: true,
          messageContent: 'Merci de faire appel au support de **{server}**.',
          embed: {
            enabled: true,
            title: 'Assistance Disponible',
            description: 'Un problème ? Utilisez le bouton Ouvrir un Ticket.',
            color: '#3B82F6',
            authorName: '{server}',
            authorIconUrl: null,
            footer: '{server}',
            footerIconUrl: null,
            thumbnailUrl: null,
            imageUrl: null,
            showTimestamp: true,
            showThumbnail: true,
            fields: [],
          },
          buttons: [],
        },
        conditions: {
          enabled: false,
          minAccountAgeDays: 0,
          requireVerificationBeforeWelcome: false,
          requiredRoleIds: [],
          excludedRoleIds: [],
        },
        autoRoleIds: [],
      },
    },
  },
  {
    id: 'tpl-minimal',
    name: 'Minimaliste & Épuré',
    category: 'Minimal',
    description: 'Un message simple, propre et direct sans encombrer les salons.',
    badge: 'Léger',
    previewColor: '#71717A',
    config: {
      welcome: {
        enabled: true,
        channelId: null,
        messageContent: '👋 Bienvenue {user} sur **{server}** !',
        mentionUser: true,
        sendForBots: false,
        embed: {
          enabled: false,
          title: '',
          description: '',
          color: '#71717A',
          authorName: '',
          authorIconUrl: null,
          footer: '',
          footerIconUrl: null,
          thumbnailUrl: null,
          imageUrl: null,
          showTimestamp: false,
          showThumbnail: false,
          fields: [],
        },
        image: {
          enabled: false,
          template: 'minimal',
          titleText: 'WELCOME',
          subtitleText: '{username}',
          tagText: '#{membercount}',
          accentColor: '#71717A',
          customBackgroundUrl: null,
        },
        buttons: [],
        dm: {
          enabled: false,
          messageContent: '',
          embed: {
            enabled: false,
            title: '',
            description: '',
            color: '#71717A',
            authorName: '',
            authorIconUrl: null,
            footer: '',
            footerIconUrl: null,
            thumbnailUrl: null,
            imageUrl: null,
            showTimestamp: false,
            showThumbnail: false,
            fields: [],
          },
          buttons: [],
        },
        conditions: {
          enabled: false,
          minAccountAgeDays: 0,
          requireVerificationBeforeWelcome: false,
          requiredRoleIds: [],
          excludedRoleIds: [],
        },
        autoRoleIds: [],
      },
    },
  },
];
